leanprover-community/batteries

- lean-toolchain
(This one contains a bugfix that I hope will unbork my VSCode.)
> chore: bump lean 2022-10-09

- Std/Tactic/Lint/Simp.lean
- test/lintsimp.lean
Catches the error in:
https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/simp.20timeing.20out/near/309563356
> feat: lint for simp-lemmas with variable lhs after whnf

- Std/Data/Nat/Basic.lean
Replacement for #21 to separate implementation from lemmas
> feat: Nat.sqrt

- lean-toolchain
> bump nightly-2022-11-25

- README.md
stolen from [this zulip discussion](https://leanprover.zulipchat.com/#narrow/stream/348111-std4/topic/local.20documentation.3F/near/313557776)
> chore: improve readme section for generating and serving documentation

- Std/Tactic/Lint/Simp.lean
This fixes the regression introduced in 52c2324923b7f83e4e9b82ca9c8284f7a86bd3e8
> fix: make simp linter error interactive again

- Std/Data/Rat/Basic.lean
https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Rat.2Efloor
> fix: definitions of Rat.floor and Rat.ceil

- Std.lean
- Std/Data/Array/Basic.lean
- Std/Data/Array/Merge.lean
- Std/Data/Ord.lean
Also adds some miscellaneous definitions for subarrays.
---
Depends on #48
> feat: add functions for merging arrays

- Std/Lean/Meta/Basic.lean
---
Gabriel helped me write this, so I'm fairly confident that it is correct.
> feat: add Lean.MVarId.getMVarDependencies

- Std/Classes/Order.lean
- Std/Data/Array/Init/Lemmas.lean
- Std/Data/Array/Lemmas.lean
- Std/Data/Ord.lean
- Std/Lean/Meta/DiscrTree.lean
- lean-toolchain
> chore: update to 2023-01-10 nightly

- Std/Data/Option/Lemmas.lean
Statement pulled from mathlib4.
> feat: Option.map_eq_bind

- Std/Logic.lean
Adds decide_eq_decide_iff_iff. Statement pulled from mathlib4.
> feat: decide_eq_decide_iff_iff

- Std/Data/String/Lemmas.lean
Rename `Iterator.hasNext_cons_add_csize` `Iterator.hasNext_cons_addChar`.
> fix: change theorem name

- Std/Data/List/Lemmas.lean
Add `List.Sublist.append_left`.
> feat: add a theorem about sublists

- Std/Data/List/Basic.lean
- Std/Tactic/Lint/Frontend.lean
- Std/Tactic/Lint/Misc.lean
- Std/Tactic/ShowTerm.lean
Just a cute little feature for quickly replacing tactic proofs with proof terms
also a few other unrelated doc tweaks
> feat: add a by? macro

- Std/CodeAction/Attr.lean
- Std/Lean/Parser.lean
- Std/Tactic/Basic.lean
- Std/Tactic/Congr.lean
- Std/Tactic/Ext.lean
- Std/Tactic/Ext/Attr.lean
- Std/Tactic/HaveI.lean
- Std/Tactic/Lint/Basic.lean
- Std/Tactic/NormCast/Lemmas.lean
- Std/Tactic/OpenPrivate.lean
- Std/Tactic/RCases.lean
- Std/Tactic/SeqFocus.lean
- Std/Tactic/SqueezeScope.lean
- Std/Util/ExtendedBinder.lean
Fixes a bunch of spacing issues. Waiting for the next nightly, containing leanprover/lean4#2240.
> fix: spacing issues

- Std/Data/Nat/Gcd.lean
This fixes a search and replace issue from #169.
> Restore accidentally mangled name

- Std/Data/Nat/Lemmas.lean
This is a first step in cleaning up Nat lemmas. I just moved things around to reorganize into sections. There were no other changes whatsoever!
> chore: reorganize Nat lemmas

- Std/Data/String/Lemmas.lean
Add "Mario Carneiro" to the list of the authors.
> doc: add author name to list

- Std/Data/List/Lemmas.lean
> fix: `List.mem_reverse` implicit args

- Std/Tactic/Basic.lean
- test/absurd.lean
Handy little tactic to "smartly" apply `absurd`.
> feat: add `absurd` tactic

- Std/Data/String/Basic.lean
- Std/Data/String/Lemmas.lean
> feat: add String to Substring coercion

- .github/workflows/merge_conflicts.yml
The token will be set up via separately.
> chore: enable merge conflicts bot

- Std.lean
- Std/Data/Array/Match.lean
- Std/Data/String/Basic.lean
- test/kmp_matcher.lean
A versatile implementation of the Knuth-Morris-Pratt matching algorithm.
> feat: KMP matcher

- Std/Data/List/Basic.lean
* I need this for `exact?`
* Happy to add the supremum of `List.partitionMap` and `List.partitionM` as well if that is desirable.
> chore upstream List.partitionM

- Std/Data/Nat/Gcd.lean
- Std/Data/Rat/Basic.lean
- Std/Data/Rat/Lemmas.lean
It's a prop, so should be PascalCase.
> fix: rename Nat.coprime to Nat.Coprime

- Std/Data/Int/Lemmas.lean
- Std/Data/Rat/Lemmas.lean
I need these lemmas without Mathlib.
> feat: lemmas about Rat.instIntCast

- Std/Data/String/Lemmas.lean
not sure if they belong here or in mathlib but they seemed widely useful
> feat: some string length lemmas

- Std.lean
- Std/Lean/Float.lean
- Std/Tactic/GuardExpr.lean
- test/float.lean
> feat: add Float.{toRatParts, toStringFull}

- Std.lean
- Std/Data/BitVec.lean
- Std/Data/BitVec/Basic.lean
- Std/Data/Int/Basic.lean
- Std/Data/Nat/Init/Lemmas.lean
- test/bitvec.lean
- test/int.lean
This library was started by Joe Hendrix and Wojciech Nawrocki. It is crucial for software and hardware verification projects. We need it in `Std`. Moreover `lean-auto` project needs it.
> feat: add basic `BitVec` library

- Std/Data/Nat/Lemmas.lean
Some easy lemmas, in preparation for upstreaming more of Mathlib's bitwise lemmas.
> feat: lemmas on Nat.shiftRight

- Std/Lean/Meta/Basic.lean
- Std/Tactic/Basic.lean
- test/repeat.lean
As [reported on Zulip](https://leanprover.zulipchat.com/#narrow/stream/348111-std4/topic/Problem.20with.20.60repeat'.60/near/397447927).
> fix: `repeat'` should roll back the state

- .github/workflows/build.yml
- Std.lean
- Std/Data/Json.lean
- Std/Lean/Json.lean
- test/json.lean
---
See Zulip discussion at https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/json.20elaborator
> feat: add the json% macro from ProofWidgets4

- Std/Classes/SetNotation.lean
See the [Zulip discussion](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Forall.20x.20not.20in/near/398719328).
> feat: More extended binders for sets.

- Std/Data/Option/Lemmas.lean
The characteristic property of `getD`.
> chore: add Option.getD_eq_iff

- Std/Data/List/Lemmas.lean
- Std/Logic.lean
The full characterisation is only given for `List Nat`, as Std doesn't have the necessary order typeclasses to prove it generally. I'm using `List.minimum?` over `Nat`, so this suffices for my purposes for now. There's a comment about generalizing.
> feat: lemmas characterising List.minimum?

- Std/Data/List/Lemmas.lean
- Std/Data/Range/Lemmas.lean
- Std/Data/Rat/Lemmas.lean
- Std/Logic.lean
> feat: upstream lemmas about if-then-else

- Std/Data/List/Basic.lean
> feat: port List.traverse

- Std/Data/Array/Lemmas.lean
The corresponding lemmas about `Array.any` already exist in `Std.Data.Array.Init.Lemmas`.
> feat: lemmas characterising Array.all

- Std/Data/MLList/Basic.lean
I was told to make an easy PR so that in my other PR, CI checks would run automatically, so here it is.
> style: remove colon

- Std/Classes/LawfulMonad.lean
Replaces the majority of leanprover-community/mathlib4#8772
> feat: add `LawfulMonad` instance for `EStateM`

- Std/Data/Int/DivMod.lean
- Std/Data/Nat/Lemmas.lean
Lemmas for a `omega` preprocessor.
> feat: emod_pos_of_not_dvd for Nat and Int

- Std/Data/Int/Lemmas.lean
Also gather together the existing lemmas about `sign`.
> feat: lemmas about Int.sign

- Std/Data/Array/Basic.lean
- Std/Data/HashMap/Basic.lean
- Std/Lean/LocalContext.lean
- Std/Lean/Meta/AssertHypotheses.lean
- Std/Lean/Meta/Basic.lean
- Std/Lean/Meta/Clear.lean
- Std/Lean/Meta/Inaccessible.lean
- Std/Lean/Meta/InstantiateMVars.lean
- Std/Lean/Meta/SavedState.lean
- test/guardexpr.lean
I'll let someone else write the linter. :-)
> chore: prefer fun over 'λ'

- README.md
> doc: status labels

- Std/Data/AssocList.lean
- Std/Data/HashMap/WF.lean
I will need this for some termination proofs for operations on coefficients in `omega`.
> feat: AssocList.size

- Std/Data/List/Lemmas.lean
These are the dual statements for `List.maximum?` of existing lemmas for `List.minimum?`.
> feat: dualize List.minimum? lemmas

- Std/Tactic/RCases.lean
- test/rcases.lean
See [Zulip](https://leanprover.zulipchat.com/#narrow/stream/348111-std4/topic/.60obtain.20rfl.60.20not.20working.20when.20powers.20involved.2E/near/410761843)
> fix: synthesize pending mvars after rcases

- Std.lean
- Std/Control/Nondet/Basic.lean
- Std/Data/MLList/Basic.lean
- Std/Lean/Meta/Basic.lean
- Std/Tactic/Backtrack.lean
- Std/Tactic/SolveByElim.lean
- Std/Tactic/SolveByElim/Backtrack.lean
- test/nondet.lean
- test/solve_by_elim.lean
This ports solve_by_elim from Mathlib and backtracking as part of that.
> Port: solve_by_elim from Mathlib

- Std/Data/Array/Lemmas.lean
These three lemmas are useful for induction on array size.
> feat: three array lemmas

- Std.lean
- Std/Lean/Except.lean
- Std/Tactic/SolveByElim.lean
- Std/Tactic/SolveByElim/Backtrack.lean
Multiple tactics in Mathlib use this, so it is inconvenient to have `private`.
> feat: make Except.emoji public

- Std/Tactic/Omega/Coeffs/IntList.lean
- Std/Tactic/Omega/Frontend.lean
- Std/Tactic/Omega/Int.lean
- Std/Tactic/Omega/LinearCombo.lean
- test/omega/test.lean
> feat: omega understands multiplication on the right by a constant

- Std/Data/List/Basic.lean
- Std/Data/List/Lemmas.lean
Also add 3 lemmas about `getLast?`, `getLast`, and `getLastD`.
> feat(Data/List): deprecate `last'` and `ilast'`

- README.md
Give actionable instructions for depending on `std4`.
> doc: how to depend on the library

- Std/Data/Int/DivMod.lean
Three easy lemmas about integer divisibility.
> feat: lemmas about Int divisibility

- Std/Lean/Meta/Basic.lean
- test/isIndependentOf.lean
Happily, @JLimperg had implemented exactly the function I need here, so the fix was easy.
Fixes #424.
> chore: fix isIndependentOf (fixes #424)

- Std/CodeAction/Basic.lean
- Std/CodeAction/Misc.lean
- Std/Control/Nondet/Basic.lean
- Std/Data/Array/Init/Lemmas.lean
- Std/Data/Array/Match.lean
- Std/Data/Json.lean
- Std/Data/List/Basic.lean
- Std/Data/List/Init/Lemmas.lean
- Std/Data/List/Lemmas.lean
- Std/Data/List/Perm.lean
- Std/Data/Option/Basic.lean
- Std/Data/Prod/Lex.lean
- Std/Data/Range/Lemmas.lean
- Std/Data/String/Basic.lean
- Std/Lean/Json.lean
- Std/Lean/Meta/Basic.lean
- Std/Lean/Meta/Inaccessible.lean
- Std/Lean/Meta/Simp.lean
- Std/Lean/Meta/UnusedNames.lean
- Std/Lean/System/IO.lean
- Std/Lean/Util/EnvSearch.lean
- Std/Tactic/Case.lean
- Std/Tactic/FalseOrByContra.lean
- Std/Tactic/Lint/Basic.lean
- Std/Tactic/Omega/Coeffs/IntList.lean
- Std/Tactic/Omega/Constraint.lean
- Std/Tactic/Omega/Core.lean
- Std/Tactic/Relation/Symm.lean
- Std/Tactic/SolveByElim.lean
- Std/Util/ProofWanted.lean
> chore: reduce imports

- Std/Data/Array/Basic.lean
This is meant to be a fix for #431.
This is my first time writing lean for anyone but horrible hacky advent of code scripts, so please don't hold back with the feedback.
> Add minWith, maxWith; fix bugs in other min_ and max_ functions.

- Std/Tactic/SolveByElim.lean
#547 is causing breakages in Mathlib on `nightly-testing` and leanprover-community/mathlib4#9960. I'm going to revert it and try it again with more thorough testing next week.
This reverts commit 18e0f99c8578ab2be044206d36f1ffce0cac234e.
> chore: revert #547

- Std/Tactic/SolveByElim.lean
This reverts commit 18e0f99c8578ab2be044206d36f1ffce0cac234e.
This was accidentally unreverted in #551.
> Revert "chore: don't call symmSaturate repeatedly in solve_by_elim (#547)" again

- GNUmakefile
- test/library_search/basic.lean
- test/omega/examples.lean
Our current makefile doesn't actually run the tests in subdirectories of `test/`, and unsurprisingly some are broken!
This PR just fixes the makefile, but will fail until the tests are fixed. (Which I will do next.)
> chore: run tests in subdirectories

- Std/Tactic/Omega/Core.lean
- Std/Tactic/Omega/Frontend.lean
- Std/Tactic/Omega/OmegaM.lean
- test/omega/test.lean
Per @joehendrix's [request](https://leanprover.zulipchat.com/#narrow/stream/348111-std4/topic/.60omega.60.20did.20not.20find.20a.20contradiction/near/419179638).
> fix: omega uses local values

- Std/Tactic/Omega/OmegaM.lean
- test/omega/test.lean
```
example (i : Fin 7) : (i : Nat) < 8 := by omega
```
Noticed this was missing in #590.
> feat: omega using Fin.isLt

- Std/Data/BitVec/Lemmas.lean
- Std/Tactic/SolveByElim.lean
> chore: missing BitVec lemmas

- Std/CodeAction/Misc.lean
This replaces the original `Generate a skeleton for the structure under construction.` code action with `Generate a (minimal|maximal) skeleton for the structure under construction.`, where the `maximal` variant acts like the original one, and the `minimal` variant skips any fields that lean would not complain about. The default selection is changed to the `minimal` variant, and the distinction is not shown if the structure does not have any defaultable fields.
Before:
```lean
instance : Monad Id where
map := _
mapConst := _
pure := _
seq := _
seqLeft := _
seqRight := _
bind := _
```
After:
```lean
instance : Monad Id where
pure := _
bind := _
```
> feat: generate minimal structure instances in code action

- test/library_search/basic.lean
These tests were not being run in CI (per #585), so had broken.
> chore: update exact? tests

- Std.lean
- Std/Data/Array/Lemmas.lean
- Std/Util/CheckTactic.lean
- test/array.lean
This does some basic simp tests for arrays as well
> feat: Introduce #check_simp command and usage.

- Std/Data/BitVec/Folds.lean
- Std/Data/BitVec/Lemmas.lean
- Std/Data/Range/Lemmas.lean
- Std/Data/Rat/Lemmas.lean
- Std/Data/UInt.lean
- Std/Tactic/Omega.lean
- Std/Tactic/Omega/Coeffs/IntList.lean
- Std/Test/Internal/DummyLabelAttr.lean
I noticed a number of files with missing copyright headers, and have added them.
@joehendrix, @fgdorais, @digama0, could you please all reply in the comments your approval (as I'm listing you as authors of the relevant files).
> chore: add missing copyright headers

- Std/Data/BitVec/Lemmas.lean
shows that `BitVec.ofBool` is injective.
> feat: ofbool_eq_iff_eq

- Std/Data/Array/Lemmas.lean
- Std/Data/HashMap/Lemmas.lean
Unsure how this interacts with #279, but it's marked as `proof_wanted` so why not.
> feat: `HashMap.empty_find?` + helper lemmas

- Std.lean
- Std/Data/Array/Lemmas.lean
- Std/Data/UnionFind/Basic.lean
- Std/Data/UnionFind/Lemmas.lean
Migrating union-find implementation from Mario Carneiro's [Lean4Lean](https://github.com/digama0/lean4lean/blob/master/Lean4Lean/UnionFind.lean).
> feat: implement union-find

- Std/Data/List/Lemmas.lean
> fix: map_drop had unnecessarily specialized universes

- Std/Tactic/Init.lean
The rest of this file will follow later.
> chore: remove some already upstreamed tactics

- Std/Data/Sum/Lemmas.lean
- Std/Logic.lean
I didn't really know where to put `Function.funext_iff` because `Std/Data/Sum/Lemmas` imports `Std/Data/Sum/Basic` and nothing else. Please refactor!
> feat: Function.funext_iff and Sum.elim_eq_iff

- Std/Data/List/Basic.lean
- Std/Data/List/Lemmas.lean
> chore(Data/List): drop `removeNth`

- Batteries/Data/List/Lemmas.lean
Replace the titles with the ones in lowerCamelCase.
> doc: fix section titles

- Batteries/Data/List.lean
- Batteries/Data/List/EraseIdx.lean
- Batteries/Data/List/Lemmas.lean
Replaces leanprover-community/mathlib4#12388
> feat(Data/List/EraseIdx): new file

- Batteries/Data/Array/Lemmas.lean
This PR adds two Array lemmas for Array.shrink. This PR has downstream use in #793 
This PR affects  downstream PR #793
> feat: size lemmas for Array.shrink

- Batteries/Util/ExtendedBinder.lean
It has been upstreamed to Lean4.
> chore: remove `binder_predicate`

- Batteries/Data/List/Lemmas.lean
These are already in Mathlib, just moving them up.
> feat: missing modifyNth simp lemmas

- Batteries/Data/RBMap/Basic.lean
I'm only adding this now so we can remove material from Mathlib.
> chore(RBSet): consolidate API from mathlib

- Batteries/Data/Char.lean
- Batteries/Data/String/Lemmas.lean
- lean-toolchain
Adaptations for leanprover/lean4#4357.
> chore: adaptations for nightly-2024-06-11

- Batteries/Tactic/Lint/Frontend.lean
Relevant if https://github.com/leanprover/lean4/issues/4432 is wontfix
https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/v4.2E9.2E0-rc1.20discussion/near/443441359
> fix(linter): "(invalid MessageData.lazy, missing context)"

- Batteries/Tactic/Lint/Simp.lean
- test/lint_simpNF.lean
This reverts commit 007a82fab9671c960ad260d4e4bf664b9fb884e3.
> Revert "chore(Tactic/Lint/Simp): make simpNF linter dsimp-aware (#839)"

- Batteries.lean
- Batteries/Data/Thunk.lean
Split from #835, upstreamed from Mathlib
> feat: ext lemma for `Thunk`

- Batteries.lean
- Batteries/Data/BinaryHeap.lean
Moved from Mathlib with minimal adaptations.
> feat: add `BinaryHeap`

- Batteries/Linter/UnnecessarySeqFocus.lean
Let's see if I did not break anything!
> chore: replace `Std` with `Batteries` and recycle a doc-string

- Batteries/Data/Array/Lemmas.lean
- Batteries/Data/BinomialHeap/Basic.lean
- Batteries/Data/BinomialHeap/Lemmas.lean
- Batteries/Data/HashMap/WF.lean
- Batteries/Data/List/Basic.lean
- Batteries/Data/List/Count.lean
- Batteries/Data/List/Lemmas.lean
- Batteries/Data/List/Perm.lean
- Batteries/Data/Nat/Lemmas.lean
- Batteries/Data/RBMap/Depth.lean
- Batteries/Data/RBMap/Lemmas.lean
- Batteries/Data/Range/Lemmas.lean
- Batteries/Data/String/Lemmas.lean
- test/case.lean
For https://github.com/leanprover/lean4/pull/4557 CI
> fix: adapt to `Nat.add_assoc'`

- Batteries/Data/Array/Basic.lean
- Batteries/Data/List.lean
- Batteries/Data/List/Init/Attach.lean
- Batteries/Data/List/Perm.lean
- Batteries/Data/Range/Lemmas.lean
- lean-toolchain
Ugh, this should not have been merged to master.
> Revert 'chore: adaptations for nightly-2024-07-01 (#870)'

- Batteries/Data/Array/Lemmas.lean
As the title says, this adds an API lemma `mem_empty`.
> feat: Array lemma for empty map added

- Batteries/Data/LazyList.lean
Per https://github.com/leanprover-community/batteries/pull/835#issuecomment-2221717519
> chore: deprecate LazyList

- Batteries/Data/String/Lemmas.lean
Rename theorems whose statement includes `Char.utf8Size`.
> refactor: rename theorems about `Char.utf8Size`

- Batteries/Data/HashMap/WF.lean
> chore: squeeze a simp in HashMap/WF

- .github/workflows/test_mathlib.yml
> chore: fix test_mathlib.yml

- .github/workflows/build.yml
- lakefile.lean
Per discussion with Mario and Mac last night.
> chore: simplify lakefile

- Batteries/Data/Vector/Basic.lean
- Batteries/Data/Vector/Lemmas.lean
- Batteries/Lean/HashSet.lean
- test/vector.lean
> feat: decidable quantifiers for `Vector`

- Batteries/Data/List/Perm.lean
Also make `List.nil_subperm` simp
From LeanCamCombi
> feat: `l <+~ [] ↔ l = []`

- Batteries/Data/Nat.lean
- Batteries/Data/Nat/Bisect.lean
General purpose bisection algorithm.
> feat: add bisection algorithm

- Batteries.lean
- Batteries/Data/UnionFind/Basic.lean
- Batteries/Util/Panic.lean
There's no existing place to put this. Probably belongs upstream.
> chore: move panicWith out of UnionFind

- Batteries/Data/DList/Basic.lean
- Batteries/Data/DList/Lemmas.lean
> chore: cleanup of DList api

- Batteries.lean
- Batteries/Tactic/HelpCmd.lean
- test/help_cmd.lean
[Zulip discussion](https://leanprover.zulipchat.com/#narrow/stream/348111-batteries/topic/Upstreaming.20.23help.20command.3F/near/473358619)
Co-authored-by: Mario Carneiro <di.gama@gmail.com>
> feat: add `#help` commands

- Batteries.lean
- Batteries/Tactic/Trans.lean
- test/trans.lean
> feat: add `trans` tactic

- Batteries/Data/Rat.lean
- Batteries/Data/Rat/Basic.lean
- Batteries/Data/Rat/Float.lean
This separates the algebraic bits from the (basically unverifiable) numerical bits.
> chore(Data/Rat): move Float functions to separate file

- .github/workflows/nightly_detect_failure.yml
This PR copies across the bot from Mathlib that posts a reminder to create a PR to the `bump/v4.X.0`, and provides the script to automate that process.
> chore: post reminder to create adaptation PR

- .github/workflows/build.yml
> fix: don't build multiple times

- .github/workflows/nightly_detect_failure.yml
This copies across some upgrades from the Mathlib bot, and hopefully fixes the current CI failures which have caused this bot to not operate on Batteries.
> chore: update nightly-testing bot

- Batteries/Lean/EStateM.lean
- Batteries/Lean/LawfulMonadLift.lean
> fixes for testing branch `lean-pr-testing-7301`

- Batteries/Data/List/Basic.lean
> doc: Fix typo

- Batteries/Classes/SatisfiesM.lean
> chore(Classes/SatisfiesM): generalize `Applicative` -> `Functor`

- lean-toolchain
- **create bump/v4.18.0 branch, with nightly toolchain**
- **chore: adaptations for nightly-2025-02-05 (#1121)**
- **chore: adaptations for nightly-2025-02-06 (#1123)**
- **chore: adaptations for nightly-2025-02-08 (#1127)**
- **chore: adaptations for nightly-2025-02-12 (#1132)**
- **chore: adaptations for nightly-2025-02-13 (#1133)**
- **chore: adaptations for nightly-2025-02-14 (#1134)**
- **chore: adaptations for nightly-2025-02-16 (#1138)**
- **chore: adaptations for nightly-2025-02-17 (#1139)**
- **chore: adaptations for nightly-2025-02-19 (#1140)**
- **chore: adaptations for nightly-2025-02-20 (#1142)**
- **chore: adaptations for nightly-2025-02-24 (#1144)**
- **chore: adaptations for nightly-2025-02-25 (#1145)**
- **chore: adaptations for nightly-2025-03-01 (#1147)**
- **chore: …
> chore: bump toolchain to v4.18.0

- Batteries/Data/Rat/Basic.lean
- Batteries/Data/Rat/Lemmas.lean
Makes `Rat` exclusively use `divExact` for normalization.
Closes #1202
> perf: make `Rat` use `divExact` for normalization

- Batteries/Data/HashMap/Basic.lean
> chore: deprecate LawfulHashable

- Batteries/Data/Array/Lemmas.lean
- Batteries/Data/List/Lemmas.lean
- Batteries/Data/Vector/Lemmas.lean
These match the API for `Array` in https://github.com/leanprover/lean4/pull/7913.
Motivated by [#Is there code for X? > Concrete permutation @ 💬](https://leanprover.zulipchat.com/#narrow/channel/217875-Is-there-code-for-X.3F/topic/Concrete.20permutation/near/522461859)
> chore(Data/Vector): lemmas about finIdxOf?

- BatteriesTest/lint_simpNF.lean
> adaptation for lean pr 9304

- Batteries/Data/Char.lean
This PR adds lemmas relating `Char.isLower`, `Char.isUpper`, `Char.toLower`, `Char.toUpper`.
> feat: add ASCII character casing lemmas

- Batteries/Data/Nat/Gcd.lean
Using `let` doesn't make sense to me here since the return type is a `Prop`.
> chore: replace a `let` with `have`

- Batteries/Control/Lemmas.lean
These should really be in core, but so should everything in this file.
> feat: lemmas about `throw` and `tryCatch` for `ReaderT` and `StateT`

- Batteries/Data/Fin/Lemmas.lean
Surprisingly, I couldn't find these trivial lemmas anywhere.
> chore: forward port of lean4#10627
