leanprover-community/batteries

- Std/Logic.lean
The higher order `forall₂_congr` lemmas in mathlib are dependently typed (and also go one higher). Can we do them here, rather than have this split between here and mathlib?
> chore: mathlib compatible forall₂_congr and higher

- Std/Data/Array/Init/Lemmas.lean
- Std/Data/BinomialHeap.lean
- Std/Tactic/Ext/Attr.lean
- Std/Tactic/Lint/Simp.lean
- lean-toolchain
I'd like to get up to nightly-2022-11-17, as it has some fixes we need in mathlib4.
There's a broken proof here in HashMap/WF.lean, at `WF.filterMap`.
> chore: bump to nightly-2022-11-17

- Std/Data/RBMap/Basic.lean
I think this was just a copy/paste typo, unless I'm missing something. `RBMap.any` is defined using `RBSet.all`, but it probably should be `RBSet.any`.
> fix: change RBMap.any to use RBSet.any

- Std/Tactic/Ext.lean
- test/ext.lean
This matches Lean 3 behaviour, and seems both more helpful to end users and to tactics that use `ext`.
> chore: ext should fail if no progress

- Std.lean
- Std/Data/Char.lean
- Std/Data/Nat/Lemmas.lean
- Std/Data/String.lean
- Std/Lean/Meta/UnusedNames.lean
This is a variant of `LocalContext.getUnusedName` which (a) may or may not be more efficient and (b) allows us to get multiple unused names in one go.
> feat: add Lean.Meta.getUnusedNames

- Std.lean
- Std/Lean/Meta/Basic.lean
- Std/Lean/Meta/Clear.lean
This is a variant of core's `tryClearMany` which sorts the given `FVarId`s by context order before trying to clear them. This makes sure we clear everything we can.
Depends on #42
> feat: add Lean.MVarId.tryClearMany'

- Std.lean
- Std/Lean/Meta/AssertHypotheses.lean
This is a variant of core's `assertHypotheses` which allows us to specify the `BinderInfo` and `LocalDeclKind` of the asserted hypotheses.
Depends on #42
> feat: add Lean.MVarId.assertHypotheses' 

- README.md
- lakefile.lean
Generate documentation with `lake -Kdoc=on build Std:docs`.
See also the [relevant zulip thread][zulip].
[zulip]: https://leanprover.zulipchat.com/#narrow/stream/348111-std4/topic/local.20documentation.3F
> chore: add doc-gen4 facet to lakefile

- Std.lean
- Std/Classes/Cast.lean
- Std/Data/Int/DivMod.lean
- Std/Data/Int/Lemmas.lean
- Std/Tactic/NormCast/Lemmas.lean
This introduces the `Nat.cast` function (without any lemmas, purely as notation), and changes the simp normal form of `Int.ofNat` to `Nat.cast` (with an appropriate `NatCast Int` instance). We need to test that this works on mathlib4 before merging this.
> refactor: Use Nat.cast in place of Int.ofNat

- Std/Data/List/Lemmas.lean
Lemmas that turn getLast and its variants into getLastD are unworkable in the context of mathlib,
where there are a lot of lemmas about the former
but none about the latter (since it had no Lean 3 equivalent).
> fix: remove simp attribute from getLastD-related lemmas

- Std/Tactic/Lint/Simp.lean
This fixes an issue discovered in leanprover-community/mathlib4#966.
> fix: ignore optParam in simpNF conditional detection

- Std/Lean/Expr.lean
Also add `forallArity` and `lambdaArity`.
> feat: add mdata-safe variants of some Expr functions

- Std.lean
- Std/Data/HashMap/Basic.lean
- Std/Lean/HashMap.lean
- Std/Lean/HashSet.lean
- Std/Lean/PersistentHashMap.lean
- Std/Lean/PersistentHashSet.lean
With the changes in this commit, the APIs for the various set and map types are consistent:
- Lean.HashMap and Lean.PersistentHashMap have the same API as Std.Data.HashMap and Std.Data.PersistentHashMap.
- Lean.HashSet has the same API as Lean.PersistentHashSet.
> feat: more API for Lean.{Persistent,}Hash{Map,Set}

- Std/Data/Array/Basic.lean
---
Depends on #48 
The `max`/`min` variants use a convention which I've established in my own code: `Ord` instances (and `BEq`, `LT` etc.) are always named. This makes it easy to give a non-standard order, but it makes the unused arguments linter unhappy.
> feat: add Array.{equalSet,qsortOrd,min,max}

- Std/Data/Rat/Basic.lean
This PR would hide the Rat division instance behind a layer `Rat.div`, so that it doesn't get unfolded to `a * b.inv` when working at the level of instance transparency.  This ensures that `Rat` behaves the same way as a generic `LinearOrderedField` in examples such as the following:
```lean
import Mathlib.Data.Rat.Order
variable [LinearOrderedField α]
/- `.reducible` transparency works correctly over `ℚ`. -/
example {a b : ℚ} : a / 2 ≤ b / 2 := by
with_reducible (apply mul_le_mul) -- fails, as desired
/- `.instance` transparency works correctly over a generic field. -/
example {a b : α} : a / 2 ≤ b / 2 := by
with_reducible_and_instances (apply mul_le_mul) -- fails, as desired
/- `.instance` transparency does not work correctly over `ℚ`. -/
example {a b : ℚ} : a / 2 ≤ b / 2 := by …
```
> chore: don't inline `Rat.div` definition, for better instance transparency behaviour

- Std/Util/LibraryNote.lean
This is the format used throughout mathlib; I don't know if there are any other library_note users.
> doc: adjust library_note example

- Std/Logic.lean
Adds `forall_exists_index`. Statement pulled from mathlib4.
> feat: forall_exists_index

- Std.lean
- Std/Classes/Cast.lean
- Std/Classes/RatCast.lean
This is used for leanprover-community/mathlib4#1707.
This also makes `Nat.cast`, `Int.cast`, and `Rat.cast` reducible.
We:
* move `RatCast` into std4
* define `Rat.cast` and give it coercion instances, in parallel to `Int.cast` and `Nat.cast`
* add reflexive instances for `NatCast`, `IntCast`, and `RatCast` (e.g. `NatCast Nat where natCast x := x`)
* add `@[reducible]` to (`Nat`/`Int`/`Rat`)`.cast`
> feat: move `RatCast` into std4

- Std/Classes/Cast.lean
- Std/Data/Int/Lemmas.lean
Not tested, I'm hoping CI will do that.
> fix: prevent `Int.ofNat` being used instead of `Nat.cast`

- Std/Data/Rat/Basic.lean
- Std/Data/Rat/Lemmas.lean
We make `Rat.ofScientific` irreducible to prevent it from being unfolded during defeq checks in which we'd rather unfold e.g. `RatCast.ratCast` on the rhs. See [zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/finishing.20up.20ofScientific.20in.20norm_num).
> feat: make `Rat.ofScientific` `@[irreducible]`

- Std/Data/Option/Basic.lean
We pretty much always want option methods to be inlined, and all the ones in core are already marked as such. In addition to enabling optimizations, this also fixes the bug in https://github.com/leanprover-community/mathlib4/pull/3509 , because after inlining `Option.get none` lean doesn't think that the resulting `unreachable` is a good target for extraction anymore.
cc: @gebner , do you see any issues here? Do we need a mathlib4 perf run?
> fix: add more @[inline] to Option methods

- Std.lean
- Std/WF.lean
Lean 4 code generator has had no native supports for `Acc.rec`.
This PR makes `Acc.rec` computable.
This change makes many defs computable, like `WellFounded.fix`.
> feat: make `Acc.rec` and many related defs computable

- Std/Tactic/GuardExpr.lean
- test/guardexpr.lean
This adds `#guard_expr`, which is a command version of the `guard_expr` tactic
Furthermore, this adjusts the handling of expected types so that when synthetic metavariables are synthesized then instances are more likely to be correct. This affects numeric literals for example, which otherwise might become `Nat`s due to the default instance.
Lastly, adds a `#guard` command that uses the evaluator to check if the given expression evaluates to true.
This PR is moving commands defined in a testing file from [mathlib4#3427](https://github.com/leanprover-community/mathlib4/pull/3427) to std4.
> feat: `#guard_expr` command and adjust handling of expected types for `guard_expr` tactics

- Std/Data/Char.lean
- Std/Data/String/Basic.lean
Zulip discussion: https://leanprover.zulipchat.com/#narrow/stream/348111-std4/topic/.60Char.2Ecsize_pos.60.20and.20.60String.2Ecsize_pos.60.20are.20the.20same
> fix: rename theorems on `String.csize`

- Std/Data/Nat/Lemmas.lean
- Std/Data/String/Lemmas.lean
- lean-toolchain
* Rename the theorem `String.addString_eq` `String.addString_byteIdx`.
* Add new theorems to `Data.Nat.Lemmas` and `Data.String.Lemmas`.
* Move lemmas from `Mathlib.Data.String.Basic` to here.
> feat: change and add theorems on `String`

- Std/Data/Char.lean
- Std/Data/Nat/Lemmas.lean
- Std/Data/String/Lemmas.lean
* Clean up code.
* Move `Nat.add_pos_left` and `Nat.add_pos_right` from `Mathlib.Data.Nat.Order.Basic` to `Std.Data.Nat.Lemmas`.
* Add lemmas to `Data.String.Lemmas`.
* Rename `String.extract.go₁_zero_endPos` `String.extract.go₁_zero_utf8Len`.
* Fix the statements of `Substring.next_cons_zero`, `Substring.next_cons_addChar`, and `Substring.nextn_cons_addChar`.
> fix: clean up `Data.String.Lemmas`

- Std/Data/String/Lemmas.lean
This theorem will be used to prove a theorem about `String.ltb` in `Mathlib.Data.String.Basic`.
> feat: add a theorem about `String.Pos`

- Std.lean
- Std/Lean/Name.lean
- Std/Lean/Position.lean
- Std/Tactic/ShowTerm.lean
- Std/Tactic/TryThis.lean
Adds proper widget / code action support for "try this" prompts in tactics. Still open: merging the widget into the message itself, depends on leanprover/lean4#2064 .
> feat: 'Try this' support

- Std/Data/String/Lemmas.lean
Adds the main tools for being able to prove theorems about strings. The difficult part about string manipulation is that everything uses the `Pos` type, which is not necessarily a valid UTF8 char boundary in the string, and the string functions have a variety of (mostly garbage and not at all consistent) ways to handle these invalid locations. We could painstakingly prove how each of them handles this case, but it is basically a misuse of the library so I think it is safe to just restrict to the case where the position is valid for the string.
To that end, we introduce the `Pos.Valid` type, which asserts that the position is the UTF8 length of some initial substring. We can prove some strong theorems about the behavior of all the main functions, but with awkward input values. The …
> feat: String theorems

- Std/Tactic/Lint/Frontend.lean
- scripts/runLinter.lean
This prints linter errors in the following form:
```
./build/bin/runLinter
-- Found 1 error in 4260 declarations (plus 16946 automatically generated ones) in Std with 12 linters
/- The `synTaut` linter reports:
THE FOLLOWING DECLARATIONS ARE SYNTACTIC TAUTOLOGIES. This usually means that they are of the form `∀ a b ... z, e₁ = e₂` where `e₁` and `e₂` are identical expressions. We call declarations of this form syntactic tautologies. Such lemmas are (mostly) useless and sometimes introduced unintentionally when proving basic facts using `rfl`, when elaboration results in a different term than the user intended. You should check that the declaration really says what you think it does. -/
-- Std.Tactic.Lint.Frontend
./Std/Tactic/Lint/Frontend.lean:137:1: error: Std.Tactic.Lint.h LHS equals …
```
> feat: make linter output errors using errorformat

- Std.lean
- Std/Tactic/Instances.lean
- test/instances.lean
This adds a command similar to `#synth` that finds all applicable instances. For example, `#instances Add _` looks for all instances whose conclusion unifies with `Add _`. Trailing underscores can be omitted, so `#instances Add` works as well. Another example is `#instances OfNat _ (nat_lit 0)`, which shows all instances of `OfNat` for `0`.
> feat: `#instances` command to find applicable instances

- Std/Data/Nat/Lemmas.lean
The corresponding lemmas in Mathlib are based on a monoid class (Mathlib/Algebra/GroupPower/Basic.lean) so they won't be down-ported to Std. Core has very limited need for powers, so they are unlikely to appear there.
> Basic pow lemmas for Nat

- Std/Data/Nat/Lemmas.lean
This protects all the the newly added theorems from https://github.com/leanprover/std4/pull/154 that collide with root theorems in mathlib4. (`pow_add'` does not exist in the root namespace, but it seems weird to promote just this one!)
> chore: protect newly added theorems in Nat namespace that collide with root theorems in mathlib4

- Std/Data/Option/Basic.lean
The `show` and `have` are because the derive handler in core makes the actual implementation of `BEq` private, which means it can't be unfolded easily. Fortunately, it's pretty easy to figure out what it does in this particular case.
> feat: `LawfulBEq` instances for `Option` types

- Std/Tactic/Congr.lean
- test/congr.lean
The `MetaM` version of `congr` (`Lean.MVarId.congrN`) has 2 configs: `closePre` and `closePost`.
Especially, `closePost` is significant to prevent timeout.
This file adds a config for the `congr` & `rcongr` tactic.
> feat: additional config for `congr`

- Std/Tactic/Ext.lean
This is relevant for `@[ext]` lemmas in mathlib4 such as 
```
theorem ext {X Y : PresheafedSpace C} (α β : X ⟶ Y) (w : α.base = β.base)
(h : α.c ≫ whiskerRight (eqToHom (by rw [w])) _ = β.c) : α = β :=
```
We usually apply these using `fapply`, as one needs to solve `w` before `h`. It would be nice to have `ext` be helpful on this.
> chore: ext doesn't reorder goals

- Std/Data/Fin/Basic.lean
- Std/Data/Fin/Lemmas.lean
- Std/Data/Nat/Lemmas.lean
- Std/Data/Range/Lemmas.lean
- Std/Data/String/Lemmas.lean
- Std/Logic.lean
A WIP branch for porting Mathlib.Data.Fin.Basic to std.
> feat: Data.Fin.Lemmas <- mathlib

- Std/Data/Int/DivMod.lean
I needed this variant of `Int.fmod_nonneg` with a weaker condition on `a` and a stronger condition on `b`.  Not sure if Std is yet in the "accepting random useful lemmas" stage of its existence, but I'm passing it along in case it is.
> `Int.fmod_nonneg` variant

- Std/Data/List/Basic.lean
includes csimp lemma to substitute the tailrec version
> feat: tailrec pmap

- Std/Data/List/Basic.lean
- Std/Data/List/Lemmas.lean
The main purpose here is to provide `union_def` and `inter_def`, so no one has to call simp with the auto-generated instance name. (Supporting https://github.com/leanprover/lean4/issues/2343.)
I've also restated the lemmas about inter and union in terms of the notation, but I'm happy to roll that part back if preferred.
> chore: union_def and inter_def lemmas

- Std/Tactic/Lint/Misc.lean
- test/lintunused.lean
> feat: ignore sorries in unused argument linter

- Std/Data/String/Lemmas.lean
Move a theorem from `Mathlib.Data.String.Basic` to Std.
> feat: move a theorem about string iterators

- Std/Data/Nat/Basic.lean
- Std/Data/Nat/Lemmas.lean
Added recursors that use `0` and `_+1` instead of `Nat.zero` and `Nat.succ`.
Added strong recursors.
Added diagonal recursors for two variables.
Added lemmas for these recursors.
> feat: custom recursors for `Nat`

- Std/Tactic/Basic.lean
- test/conv_equals.lean
Given a goal `a * b`, I find myself wanting for a concise way of specifying the position of `b` (without repeating it), saying that I want to prove it to be equal to `c`, then doing the proof of `b = c`, and end up with `a = c`. Of course the terms can be larger and more deeply nested, possibly in binders.
So here is a tactic that does that.
I think it is a very natural way of interactive proving. Stare at the goal, notice a subexpression where you can make progress, focus, say what you want to rewrite it to, prove the rewriting, all with DRY.
It’s basically the less pretty; less verbose style version of a nice `calc` proof, without the repetition and the `:= by congr 3; …` before the actual proof steps.
Or the equivalent of the pen-and-paper style of putting curly braces under some …
> New conv tactic: equals

- Std/Data/MLList/Basic.lean
Additional helpers for running a monadic lazy lists in transformers.
> feat: run `MLList`s in `ReaderT` or `StateRefT'`

- Std.lean
- Std/Data/List/Basic.lean
- Std/Data/List/Count.lean
Moves `Mathlib/Data/List/Count.lean` to Std. I believe there are no notable changes from mathlib, aside from dropping various lemmas about prod.
Depends on ~~#98 #96 #94 #97~~. EDIT: all merged :)
> chore: de-mathlib Data/List/Count.lean

- Std.lean
- Std/Lean/Util/Path.lean
- scripts/runLinter.lean
We define `ToExpr SearchPath` by hand, as we have decided not to upstream the `ToExpr` derive handler for now.
> feat: upstream `compile_time_search_path%` term elaborator

- Std.lean
- Std/Data/MLList/Heartbeats.lean
- Std/Lean/CoreM.lean
I appreciate this may seem slightly esoteric, but it is used in `apply?`, to prefer giving a "best available" answer to the user in situations where `apply?` runs for a long time, rather than crashing out with a timeout.
> chore: upstream MLList.whileAtLeastHeartbeatsPercent

- .github/workflows/merge_conflicts.yml
My first attempt to fix this didn't work as expected for this setup. (Since the `MERGE_CONFLICTS_TOKEN` simply doesn't exist on forks, it triggers a missing input error instead of a missing permissions error. So the `continueOnMissingPermissions` flag doesn't end up doing anything.)
I tested this second attempt more carefully on my end. It emits `run skipped` instead of `run failed`. That's still a bit of noise but it's easier to ignore (and it is arguably more accurate than continuing after failure). Assuming it doesn't break anything on your end (it shouldn't) then I'm completely happy with this solution.
> fix: merge conflict bot

- Std/Data/List/Basic.lean
- Std/Data/List/Lemmas.lean
Migrates `List.Sublist` decidability from Mathlib
There are efficiency concerns on the operation, so this version relies on a (tailrec) `List.isSublist` function unlike the Mathlib version.
> feat: add sublist decidability

- .github/workflows/labels-from-comments.yml
This workflow allows anyone to modify the `awaiting-review`, `awaiting-author`, and `WIP` labels, just post posting a comment containing one of those (and nothing else). The other labels from that set are automatically removed.
> feat: add workflow to allow anyone to use basic labels

- Std/Linter/UnreachableTactic.lean
- Std/Tactic/GuardMsgs.lean
- test/lint_unreachableTactic.lean
Before this change the linter would complain that `assumption` was unused
```lean
def t : ℕ → ℕ := sorry
@[simp]
lemma a : aa = 0 → t aa = 0 := sorry
lemma aaa (ha : aa = 0) : t aa = 0 := by
simp (disch := assumption)
``` 
Also have `guardMsgs` run linters so that we can test them
> feat: ignore rhs of dischargers when linting for unreachable

- Std.lean
- Std/CodeAction/Deprecated.lean
- Std/Lean/Position.lean
- Std/Tactic/Alias.lean
Now, when you declare a deprecated alias such as `@[deprecated] alias foo := bar`, occurrences of `foo` (which will be marked with a deprecation warning) will also have an auto-fix command to replace `foo` with `bar`.
> feat: code action for alias + deprecated

- Std/Tactic/Ext/Attr.lean
- test/ext.lean
This is a naive copy of the corresponding feature for `norm_num`, see https://github.com/leanprover-community/mathlib4/pull/1364; please check for pitfalls!
It passes mathlib CI:
https://github.com/leanprover-community/mathlib4/tree/hrmacbeth-bump-std
> feat: make `ext` attribute erasable

- Std/Data/HashMap/Basic.lean
- Std/Data/List/Lemmas.lean
- Std/Lean/HashSet.lean
- Std/Lean/PersistentHashMap.lean
- Std/Lean/PersistentHashSet.lean
- Std/Tactic/Alias.lean
- Std/Tactic/Basic.lean
- Std/Tactic/SqueezeScope.lean
- test/conv_equals.lean
Additional proposal:
* We still use `↦` in documentation. Let's change to some different symbol, so one can simply search for `↦` and know that every appearance is "wrong".
* Lint for this.
> chore: replace ↦ with =>

- .github/workflows/build.yml
- Std/Data/HashMap/Basic.lean
- Std/Data/List/Lemmas.lean
- Std/Lean/HashSet.lean
- Std/Lean/PersistentHashMap.lean
- Std/Lean/PersistentHashSet.lean
- Std/Tactic/Alias.lean
- Std/Tactic/Basic.lean
- Std/Tactic/SqueezeScope.lean
- test/conv_equals.lean
Simplest possible implementation of a linter forbidding `↦`. I propose not building more general infrastructure until we want it.
> chore: add grep-based linter for ↦

- Std.lean
- Std/Data/List/Lemmas.lean
- Std/Data/List/Pairwise.lean
All included statements are the same as mathlib4, but a good number of lemmas are dropped. See [diff](https://github.com/JamesGallicchio/std4/compare/TEMP_compare_pairwise..chore/move-Data/List/Pairwise.lean).
~~Depends on #99 #95.~~
> chore: de-mathlib Data/List/Pairwise.lean

- Std/Data/HashMap/Basic.lean
- Std/Data/HashMap/WF.lean
An element of the `Bucket` type is an array of buckets rather than a single bucket. I propose it should be named appropriately.
> rename: Bucket -> Buckets

- Std/Tactic/Lint/Frontend.lean
- Std/Tactic/Lint/Misc.lean
- test/lint_docBlame.lean
- test/lint_docBlameThm.lean
Some `def`s are generated by core and should really be theorems; we treat them as such in the `docBlame` and `docBlameThm` linters.
This fixes #217.
> fix: ignore `def`/`theorem` confusion in docBlame

- Std/Tactic/Lint/TypeClass.lean
- test/lintTC.lean
was https://github.com/leanprover-community/mathlib4/pull/7250/
Following https://github.com/leanprover-community/mathlib4/pull/7245, [leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/isClass.3F.20panic!/near/391779504](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/isClass.3F.20panic!/near/391779504).
> feat: a linter for instances that are not classes

- Std/Data/Nat/Gcd.lean
Consequence of smaller lemmas, but seems useful to have the `iff` packaged up for anyone needing a complete characterization of the function.
> feat: theorem characterizing Nat.gcd

- Std/Data/List/Lemmas.lean
Not sure where this came from. It's a mis-named duplicate, and not used in Mathlib.
> chore: delete stray List lemma

- Std.lean
- Std/Lean/Elab/Tactic.lean
- Std/Lean/Meta/Basic.lean
- Std/Tactic/Relation/Rfl.lean
- Std/Tactic/Relation/Symm.lean
- test/rfl.lean
- test/symm.lean
The `trans` tactic in Mathlib needs more polish than these, so I'll do that in a separate PR to ease reviewing.
> chore: upstream rfl and symm tactics

- Std/Data/List/Basic.lean
- test/list_sublists.lean
This replaces leanprover-community/mathlib4#7388, where @ChrisHughes notes
> I suspect the cause of the slowdown was the use of `Array` in `List.sublists`. An `Array` in the Kernel is just a `List`, but compiled to something more efficient. `List.sublists` uses `Array.push`, which is slow in the kernel becuase it's `l ++ [a]` on the underlying list, so it's linear time instead of constant time. So this new implementation is a better complexity in the kernel.
The difference can be seen as follows; this is fast:
```lean
set_option maxRecDepth 561 in
example : [1, 2, 3].sublists.sublists.length = 256 := rfl
```
but this hits a deterministic timeout
```lean
example : [1, 2, 3].sublistsFast.sublistsFast.length = 256 := rfl
```
---
This should not be merged until …
> perf: improve kernel reduction of `List.sublists`

- Std/Data/BitVec/Basic.lean
- test/bitvec.lean
> chore: Make signExtend use output number of bits.

- .github/nightly_bump_toolchain.yml
- .github/nightly_detect_failure.yml
- .github/nightly_merge_master.yml
Adds the following steps to CI:
* On every commit to `main`, merges `main` into `nightly-testing` (with all conflicts resolved in favour of `nightly-testing`)
* Once per day, updates `lean-toolchain` on the `nightly-testing` branch to point to the latest nightly release.
* On each CI failure on the `nightly-testing` branch, writes a message to the [mathlib reviewers](https://leanprover.zulipchat.com/#narrow/stream/345428-mathlib-reviewers) > [CI failure on the nightly-testing branch](https://leanprover.zulipchat.com/#narrow/stream/345428-mathlib-reviewers/topic/CI.20failure.20on.20the.20nightly-testing.20branch) topic.
I plan to merge `depends on core changes` labelled PRs into `nightly-testing` as the corresponding PRs to Lean land in nightly releases.
Finally, I am going to tweak the …
> chore: automation to maintain a nightly-testing branch

- .github/workflows/build.yml
- Std.lean
- Std/Lean/Util/EnvSearch.lean
- Std/Tactic/PrintPrefix.lean
- test/print_prefix.lean
This migrates #print prefix while doing some migration of functionality naming to std conventions.
This also restricts the long line check to Std.  I had some long lines in the test case file that aren't easy to fix.
> feat: Migrate #print prefix from Mathlib

- Std/CodeAction/Deprecated.lean
- Std/CodeAction/Misc.lean
- Std/Data/Fin/Lemmas.lean
- Std/Lean/Meta/DiscrTree.lean
- Std/Tactic/Ext/Attr.lean
- Std/Tactic/GuardMsgs.lean
- Std/Tactic/Instances.lean
- Std/Tactic/Lint/Simp.lean
- Std/Tactic/Relation/Rfl.lean
- Std/Tactic/Relation/Symm.lean
- Std/Tactic/TryThis.lean
- lake-manifest.json
- lean-toolchain
This should only be merged after #337.
Includes the changes from PRs #297, #306, and #316, which can be closed when this is merged.
> chore: bump toolchain to v4.3.0-rc1, incorporating changes from #297, #306, #316

- Std/Data/List/Lemmas.lean
- Std/Data/Nat/Lemmas.lean
> feat: more min/max lemmas for `Nat`

- Std/Data/Bool.lean
* fixed `le`, `lt`, `min`, `max` to be more efficient
* fixed lemma names to match naming convention
> feat: more lemmas and perf update

- Std/Data/Array/Init/Lemmas.lean
- Std/Data/Char.lean
- Std/Data/Fin/Lemmas.lean
- Std/Data/Int/DivMod.lean
- Std/Data/List/Count.lean
- Std/Data/List/Lemmas.lean
- Std/Data/Nat/Lemmas.lean
- Std/Data/Rat/Lemmas.lean
- Std/Logic.lean
Adapt to new default in Lean master.
> chore: fixes for new simp default (`decide := false`) (lean4#2722)

- Std/Data/Array/Lemmas.lean
- Std/Data/List/Lemmas.lean
- Std/Data/Nat/Lemmas.lean
There are two potentially breaking changes here:
* `Nat.le_pred_of_lt` was changed to use `pred` instead of `_-1` and `Nat.le_sub_one_of_lt` was added as a replacement.
* Implicit parameters for `Nat.eq_zero_of_nonpos`.
> feat: more succ/pred lemmas for `Nat`

- Std/Data/Array/Init/Lemmas.lean
- Std/Data/Nat/Init/Lemmas.lean
- Std/Data/Nat/Lemmas.lean
There are lots and lots of synonyms here! I didn't remove any but I did try to group them together.
> feat: more order lemmas for `Nat`

- .github/workflows/nightly_detect_failure.yml
We already do this on Mathlib.
The idea is to have known good commits on the `nightly-testing` branch for each nightly release. This makes it much saner when creating `lean-pr-testing-NNNN` branches, because we can use an appropriate commit from `nightly-testing` that is known to work on the Lean nightly on which the Lean PR is based.
> chore: create nightly-testing-YYYY-MM-DD branches when nightly-testing passes CI

- .github/workflows/nightly_bump_toolchain.yml
- .github/workflows/nightly_merge_master.yml
These workflows don't make sense on forks and should only run if the repository owner is `leanprover`.
> fix: github nightly workflow shouldn't run on forks

- Std/Logic.lean
This change was made in mathlib3 around a year and a half ago: https://github.com/leanprover-community/mathlib/commit/d787d4990bac1c8d0bbd8043a1d47fd318e9a5ba, but it was seemingly missed in the port and subsequent upstreaming of logic lemmas.
(This missing simp lemma was found in the exponential ramsey project)
> chore: generalise `exists_eq_right_right`

- Std/Data/BitVec/Basic.lean
Define specializations of `BitVec.append` to add a single bit to a bitvector, either as the new LSB or the new MSB.
I've opted to name these functions `cons` and `concat`, to be consistent with the naming of (morally) similar functions on `List`, and following the big-ending convention set in `append`.
There has previously been some discussion about not assuming a specific order. Some alternative naming (in order of my preference):
* `consMsb` / `concatLsb` : keep the `cons`/`concat` contrast, and the big-endian assumption it carries, but make explicit whether the new bit is the new MSB or LSB.
* `consMsb` / `consLsb`: to be truly neutral w.r.t. to the big vs little endian question.
The intention is to eventually define recursion principles in terms of these functions, so it's desirable …
> feat: define `cons` and `concat` on bitvectors.

- .gitignore
- GNUmakefile
- Std/Classes/LawfulMonad.lean
- Std/Data/Array/Init/Lemmas.lean
- Std/Data/Char.lean
- Std/Data/Fin/Lemmas.lean
- Std/Data/Int/DivMod.lean
- Std/Data/List/Basic.lean
- Std/Data/List/Count.lean
- Std/Data/List/Lemmas.lean
- Std/Data/List/Pairwise.lean
- Std/Data/Nat/Lemmas.lean
- Std/Data/Rat/Lemmas.lean
- Std/Logic.lean
- lean-toolchain
- test/add_suggestion.lean
- test/by_contra.lean
This combines the changes from #331 and #356.
> chore: bump toolchain to v4.3.0-rc2

- Std/WF.lean
Sometimes, a function using `Acc.rec` causes a stack overflow because the function is not specialized.
This PR specializes `Acc.rec` and `WellFounded.fix`, and inline functions depending this.
> refactor: specialize `Acc.rec` and `WellFounded.fix`

- Std/Util/Cache.lean
This code was inappropriately opinionated about ensuring that the keys being inserted into a `DiscrTree` were "specific". The function `processDecl` being passed can do that itself.
> chore: DiscrTreeCache.mk uses insertCore not insertIfSpecific

- Std.lean
- Std/Control/Lemmas.lean
Handy lemmas extracted from #85 before closing that old PR.
> feat: lemmas for ReaderT and StateT

- Std/Tactic/CoeExt.lean
- test/coe.lean
This means that it becomes easier to distinguish function coercion from "normal" coercion in a goal state.
This remains opt-in downstream; the `@[coe]` attribute does not provide syntax for the `coeFun` and `coeSort` versions.
This also does not upstream the unapplied versions.
Some more discussion is [on Zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Bringing.20back.20.E2.87.91/near/401155616).
> feat: Upstream the coercion arrows from mathlib, and use them in the coe delaborator

- Std/Lean/Name.lean
- Std/Lean/Util/EnvSearch.lean
- Std/Tactic/PrintPrefix.lean
- test/print_prefix.lean
This fixes some annoyances I had with `#print prefix`.
It filters out internal and unstable auto-generated names by default, but has an options to control that.  It also prints out private declarations if the scope is explicitly named.
> feat: Improve #print prefix filtering.

- Std/Lean/Expr.lean
This is needed by both #343 and #347, so I put it into its own commit so we aren't blocking either.
> chore: Port constName and getAppFnArgs from Mathlib

- Std.lean
- Std/Data/BinomialHeap/Lemmas.lean
- Std/Data/BitVec/Basic.lean
- Std/Data/BitVec/Bitblast.lean
- Std/Data/BitVec/Folds.lean
- Std/Data/BitVec/Lemmas.lean
- Std/Data/Bool.lean
- Std/Data/Fin/Iterate.lean
- Std/Data/Nat/Basic.lean
- Std/Data/Nat/Bitwise.lean
- Std/Data/Nat/Lemmas.lean
- Std/Logic.lean
This is a large PR that has operations for working with Nat and BitVec as functions from indices to Bool.  In particular it builds upon work in #314 and #358
> Operations for bit representation of `Nat` and `BitVec`.

- lakefile.lean
- lean-toolchain
This is a PR to the `bump/v4.4.0`, updating the `lakefile.lean` to account for a deprecated option.
It is slightly clunky that we need the `.map (·.asCliArg)` step to translate from `moreServerOptions` to `moreLeanArgs`.
> chore: moreServerOptions instead of moreServerArgs

- Std/Util/Cache.lean
This is causing a terrible problem at Mathlib: the `exact?` and `rw?` caches are being memory mapped at every single file that imports these tactics, rather than just the ones that use these tactics.
Moreover, after nightly-2023-11-29, this causes a build failure on every file if that memory mapped cache has the wrong git hash. The "rebuild-on-failure" mode in this PR means that in the event a memory mapped cache is rejected as invalid, we (silently) rebuilt the cache.
> fix: DiscrTreeCache.mk init argument should be lazy

- Std/Data/MLList/Basic.lean
- test/MLList.lean
Fixes an issue [reported on Zulip](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/MLList.20crash/near/404755610).
> fix: Use `MLList.uncons?` to avoid stack overflow

- .github/workflows/build.yml
- lakefile.lean
This also has the new compiler to default off and uses a more declarative approach to keyword flags as I'd like `lakefile.lean` to be as declarative as possible (maybe we can upstream those parts).
> feat: Control warningAsError (default off but stays on in CI)

- Std/WF.lean
I’d like to remove support for the `termination_by'` annotation. Until
https://github.com/leanprover/std4/pull/371 it wasn't used anywhere else in
lean, std, mathlib, so this PR removes the single use of it.
It does so using the pattern that can be used to replace uses of
`termination_by'`: Using `WellFounded.wrap` one can indicate an explicit
`WellFounded` relation to use.
This also un-privates the `wfRel` instance for `WellFoundedRelation { val // Acc r val }`
which looks useful enough.
So this PR uses that pattern to avoid the use of `termination_by'` here,
and at the same time provides the necessary definitions for others, so
when Lean drops support for `termination_by'`
(https://github.com/leanprover/lean4/pull/3033), we can tell users how
migrate.
> feat: avoid termination_by', introduce WellFounded.wrap

- Std/Data/BitVec/Basic.lean
Maybe this will be irrelevant if a GMP overload appears for this...
> perf: use a faster implementation of BitVec.ofInt

- Std/Data/List/Perm.lean
This name was changed during #89, but I think incorrectly, so I'm changing it back here.
Note that Mathlib has another lemma:
```
lemma subperm_singleton_iff : l <+~ [a] ↔ l = [] ∨ l = [a]
```
(correctly named, I think), which has had to be renamed (adding a prime) temporarily to allow for name change that happened in #89.
> chore: fix name of List.singleton_subperm_iff

- Std/Data/AssocList.lean
I worry slightly that someone will say they want the relation that *doesn't* care about the ordering of key-value pairs, but that is rather harder to calculate, not `Lawful`, and ... I want this one!
> feat: (Lawful)BEq for AssocList

- Std/Lean/Meta/Basic.lean
I could inline this at the point of use in `omega`, but as it is widely used in Mathlib it seems a reasonable moment to push it to Std.
> chore: upstream Lean.MVarId.applyConst

- Std/Lean/Meta/Basic.lean
Another utility function that is used by various Mathlib tactics, and now by `omega`.
> chore: upstream getLocalHyps

- Std/Lean/Expr.lean
These are used by various Mathlib tactics, and now by `omega`, so will need to move to Std.
> feat: Expr.nat?/int? to check for numbers in normal form

- Std/Data/Int/Lemmas.lean
> chore: deprecate Int.ofNat_natAbs_eq_of_nonneg

- Std/Data/Int/Basic.lean
I'm not sure in which file this belongs.
(I'm also still a bit sad that we [decided](https://leanprover.zulipchat.com/#narrow/stream/348111-std4/topic/ToExpr.20derive.20handler/near/386476438) not to upstream the `ToExpr` derive handler from Mathlib...!)
> chore: ToExpr Int

- Std/Tactic/TryThis.lean
- test/tryThis.lean
Currently, the code action title in the lightbulb menu is hardcoded to `Try this: <prettyPrintedSuggestionText>`. This needs to be customized in various cases, such as teaching in non-English languages. This PR:
* Adds a field `toCodeActionTitle? : Option (String -> String)` to `Suggestion`, which, if provided, can be applied to the pretty-printed suggestion text and transform it as desired (note that this application occurs prior to encoding, so we only pass the resulting code action title `String`, if any, to the Json version of the `Suggestion` structure; note also that we don't want to pretty-print twice, so we take in the pretty-printed `String` as an argument instead of the `SuggestionText` itself)
* Adds an argument `codeActionPrefix? : Option String := none` to `addSuggestions` to …
> feat: "Try this:" custom code action title

- Std/Tactic/Lint/Misc.lean
- lean-toolchain
This is a PR to the `bump/v4.5.0` branch. It relies on the toolchain `leanprover/lean4:nightly-2023-12-19`.
> chore: fixes for lean4#2973

- Std/Data/RBMap/Basic.lean
- Std/Data/RBMap/WF.lean
The rename makes Lean more consistent with OCaml and Haskell, where the default `Set.map` is not monotone.
- https://v2.ocaml.org/api/Set.S.html#VALmap
- https://hackage.haskell.org/package/containers-0.6.7/docs/Data-Set.html#g:10
Note that mathlib's `Finset` also has separate `map` and `image` functions, with `map` requiring extra conditions (injectivity). I think that reasoning doesn't apply for `RBSet` as the non-monotone case is much more common, and in this case consistency with Haskell/OCaml is more valuable than with mathlib.
> feat: add non-monotone map function to RBSet

- Std/Data/Fin/Lemmas.lean
These came up in [Zulip](https://leanprover.zulipchat.com/#narrow/stream/217875-Is-there-code-for-X.3F/topic/cons.20is.20to.20snoc.20as.20Fin.2Eeq_zero_or_eq_succ.20is.20to). Let me know if there's a better place to put these lemmas.
Also, I'd be happy to mark as `@[simp]`, but I wasn't sure if we wanted to commit to pushing `rev`s in or out as simp-normal form. Pushing them in (as these lemmas do) seems natural as it's what we do with negation, but `k.rev` is `-1 - k`, not `-k`, so I'm not sure what to think.
> feat: add varous lemmas for (Fin.rev _)

- Std/Tactic/TryThis.lean
- lean-toolchain
This is a PR to the `bump/v4.5.0` branch.
It combines (thanks very much to @thorimur!) the conflicting work from #466 and @Vtec234's earlier adaptation branch.
> feat: adaptations for leanprover/lean4#2964

- Std/Data/Array/Lemmas.lean
- Std/Data/RBMap/Lemmas.lean
Using `simp [forIn]` may cause nontermination with different `simp` reduction strategies. We have the following theorem
```
@[simp] theorem forIn_eq_forIn [Monad m] : @List.forIn α β m _ = forIn := rfl
```
Then, executing `simp [forIn]` in a term containing `forIn` iterating over a `List` may cause nontermination since the theorem above will fold it again.
Remark: the reduction strategy implemented
https://github.com/leanprover/lean4/pull/3118 triggers the nontermination.
> chore: potential nontermination at `simp`

- Std/Data/UInt.lean
The proposed `[ext]` lemmas use `.toNat` instead of `.val`. I find these more useful but I don't know if there are side effects to skipping an intermediate step like that.
> feat: more UIntX lemmas

- Std/Data/Nat/Lemmas.lean
`Nat.dvd_one` is from Mathlib,
other two are special cases of general lemmas in Mathlib.
> feat: add `Nat.one_dvd`, `Nat.dvd_one`, and `Nat.zero_dvd`

- GNUmakefile
- Std/Linter/UnreachableTactic.lean
- test/lint_empty.lean
The "unreachable tactic" linter would previously assume that various parser categories were in the environment, and panic if they weren't. This caused problems when elaborating declarations in a fresh, empty environment.
> fix: don't panic when linting in empty environments

- Std/Data/BitVec/Basic.lean
- Std/Data/BitVec/Lemmas.lean
- test/bitvec.lean
This fixes a match compilation bug introduced in #366 found by @leodemoura.
Prior to #366, the code below generated a correct pattern match.
```lean
def test (i : Std.BitVec 4) :=
match i with
| 0b1000#4 => some 0
| _ => none
```
> fix: Fix timeout in bitvector pattern matches.

- Std/Data/Option/Lemmas.lean
This ensures that `(do ...) = some x` expressions simplify, by rewriting `bind` to `Option.bind` and letting `bind_eq_some` trigger.
Also tweaks the `bind x f = none` simp lemma to not use the `∈` and `∉` relations in favor of `= some` and `= none` since these trigger more simp lemmas.
> feat: more simp lemmas for `bind_eq_some`

- Std/Lean/Meta/Basic.lean
- Std/Tactic/SolveByElim.lean
Several Mathlib tactics use this, so it is not ideal to have this in `SolveByElim`.
> chore: move MVarId.note

- Std/Tactic/RCases.lean
- lean-toolchain
- test/rcases.lean
This adds support for `rcases h : e` hover info along the lines of leanprover/lean4#3084 (and it depends on that as well, hence it is targeting `bump/v4.6.0`).
>  feat: hover info for `rcases h : ...`

- Std/Lean/Meta/DiscrTree.lean
- Std/Tactic/Ext/Attr.lean
- Std/Tactic/Relation/Rfl.lean
- Std/Tactic/Relation/Symm.lean
- Std/Util/Cache.lean
- lean-toolchain
This is the adaptation PR for leanprover/lean4#3123 (which wasn't tested againgst Std/Mathlib). It needs to be reviewed and merged to the `bump/v4.6.0` branch.
I have already made these changes on the `nightly-testing` branch.
> chore: adaptations for leanprover/lean4#3123

- Std/Tactic/Omega/OmegaM.lean
- lean-toolchain
After leanprover/lean4#3132 the linter will complain about this.
> chore: remove unnecessary `have`

- Std/Logic.lean
- Std/Tactic/FalseOrByContra.lean
- Std/Tactic/Omega/Frontend.lean
- Std/Tactic/Omega/Logic.lean
- test/false_or_by_contra.lean
- test/omega/test.lean
While looking at theorems that "ought" to be proved by `omega`, I found a number of `iff` goals where one would need `constructor <;> (intros; omega)` to close the goal. This PR slightly powers up `omega` so it can do this by itself.
> feat: omega handles iff and implications

- Std/Tactic/Omega/Frontend.lean
This adds two `TacticM Unit` frontends for omega: `omegaTactic` which takes an `OmegaConfig` parameter, and `omegaDefault` which uses the default configuration. The latter can be used as an aesop rule (which must be a declaration of type `TacticM Unit`).
I've experimented a bit with this as a `get_elem_tactic` replacement, where I add `omega` as a safe rule together with some `forward` rules to bring useful facts into context before the omega call, and it works remarkably well!
> feat: add a `TacticM Unit` frontend for omega that can be used as an aesop rule

- Std/Tactic/FalseOrByContra.lean
- Std/Tactic/Omega/Frontend.lean
This fixes one of several unnecessary uses of classical axioms in `omega`.
> feat: `false_or_by_contra` uses `Decidable.byContra` if possible

- Std/Tactic/Ext.lean
Makes sure to mention that the patterns are processed using `rintro`, and makes sure `ext` mentions `ext1`.
> docs: extend docstrings for `ext` and `ext1`

- Std.lean
- Std/Lean/Meta/Basic.lean
- Std/Lean/Meta/LazyDiscrTree.lean
- Std/Tactic/LibrarySearch.lean
- Std/Tactic/Relation/Symm.lean
- test/library_search/basic.lean
This is a large PR that builds upon #343 to rename the Mathlib specific cache path and improve performance of library initialization when used without a cache.  It does this primarily by introducing a lazy discriminator tree that defers population of tree branches from initialization to first lookup.
Testing on OSX is currently showing that initializing the tree using Mathlib takes under 2 seconds and a simply query adds an additional 2-3 seconds.  It would be good to get additional information more machines (particularly Windows), but I think the timings are low enough that most users will not need caching.
> Incremental Library Search

- Std.lean
- Std/Data/BinomialHeap/Basic.lean
- Std/Data/List/Basic.lean
- Std/Lean/Meta/Basic.lean
- Std/Lean/Meta/LazyDiscrTree.lean
- Std/Logic.lean
- Std/Tactic/Ext.lean
- Std/Tactic/LibrarySearch.lean
- Std/Tactic/Relation/Symm.lean
- lean-toolchain
- test/library_search/basic.lean
This is a PR to `bump/v4.6.0`, updating some of @joehendrix's work on `DiscrTree` for the latest nightly.
Annoyingly, I wasn't able to merge `main` into `bump/v4.6.0` before starting this, so the diff is pretty messy: it includes both bringing `bump/v4.6.0` up to `main`, and the fixes. The fixes themselves (which is all that really needs reviewing) are in the single commit https://github.com/leanprover/std4/pull/536/commits/e72441d2fd4d732d370696ff7e4fa92ce06fb356.
These changes have already been merged into `nightly-testing`.
> chore: updates to DiscrTree for changes in nightly

- Std/Data/Int.lean
- Std/Data/Int/DivMod.lean
- Std/Data/Int/Gcd.lean
- Std/Data/Nat/Basic.lean
- Std/Data/Nat/Gcd.lean
We move the definition of `Nat.lcm` from `Std.Data.Nat.Gcd` to `Std.Data.Nat.Basic`, and prove a few lemmas about `Int.gcd`, which are just thin wrappers around the corresponding lemams for `Nat.gcd`, dealing with `natAbs` as necessary.
> feat: lemmas about Int.gcd

- Std/Tactic/LibrarySearch.lean
This is fixing an error in `main`, so I intend to merge immediately after CI passes.
> chore: fix missing import in Std.Tactic.LibrarySearch

- Std/Tactic/Basic.lean
- test/exfalso.lean
Before this change,
```lean
example {A} : False → A := by exfalso
```
would work, but the docstring ("converts a goal `⊢ tgt` into `⊢ False`") says it should not.
> fix: make exfalso actually do what it claims to

- .github/workflows/nightly_detect_failure.yml
This is the Std companion for https://github.com/leanprover-community/mathlib4/pull/9842
I will update https://leanprover-community.github.io/contribute/tags_and_branches.html when merged.
> chore: make nightly-testing-YYYY-MM-DD a tag, not a branch

- Std/CodeAction/Basic.lean
- Std/Lean/InfoTree.lean
- lean-toolchain
Adaptations for leanprover/lean4#3159, written by @mhuisi. These changes have already landed in `nightly-testing`: this is a PR to `bump/v4.6.0`.
> feat: adaptations for leanprover/lean4#3159

- Std/Tactic/LibrarySearch.lean
- test/library_search/basic.lean
Michael Stoll asked on [Zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/exact.3F.20.2F.20apply.3F.20.2F.20rw.3F.20.2F.20.2E.2E.2E.20.20feature.20requests/near/416994860) why
```
example {x : Int} (h : x ≠ 0) : 2 * x ≠ 0 := by std_apply? using h
```
returned nothing, even though
```
example {x : Int} (h : x ≠ 0) : 2 * x ≠ 0 := by std_apply? using h says refine Int.mul_ne_zero ?a0 h
```
This PR fixes this. (And took me way too long to come up with...)
> feat: better support for 'std_apply? using'

- Std/Tactic/SolveByElim.lean
The `symm` config option for `solve_by_elim` results in calling `symmSaturate`, to add a hypothesis `h_symm` for every hypothesis with an applicable `@[symm]` lemma.
This was being run every time we wanted to apply a lemma, rather than once at the beginning! I can't think of any reason this would be necessary, and it seems horribly inefficient.
> chore: don't call symmSaturate repeatedly in solve_by_elim

- Std/Tactic/SolveByElim.lean
- test/solve_by_elim.lean
Defines a discharger for `solve_by_elim` which uses `constructor`, and enables it, and the `intro` discharger, by default.
Combined with #549 this will allow `solve_by_elim` to solve
```
example (x : (α × (β × γ))) : (α × β) × γ := by solve_by_elim
```
> feat: solve_by_elim uses intros and constructor by default

- lean-toolchain
This is a noop as `v4.5.0` is identical to `v4.5.0-rc1`.
> chore: bump to v4.5.0

- Std/Data/List.lean
- Std/Data/List/Basic.lean
- Std/Data/List/Init/Basic.lean
- Std/Data/List/Init/Lemmas.lean
- Std/Data/List/Lemmas.lean
- Std/Tactic/Omega/IntList.lean
- Std/Tactic/Omega/LinearCombo.lean
- Std/Tactic/Omega/MinNatAbs.lean
This adds lemmas to Std.Data.List from Omega dependencies so that Omega can be used in List lemmas.
I changed a few proofs as part of this to reduce dependencies and include fewer lemmas in Init.
> chore: remove Std.Data.List import from Omega

- Std/Data/BitVec/Basic.lean
- Std/Data/BitVec/Lemmas.lean
- Std/Data/Fin/Lemmas.lean
- Std/Data/Nat/Bitwise.lean
A user was having trouble with:
```
import Std
open Std BitVec
example (v : Std.BitVec n)  : 0#0 ++ v = BitVec.cast (by omega) v := sorry
```
With these changes:
* add `@[ext]` to `BitVec.eq_of_getLsb_eq`
* add `@[simp]` to a few existing lemmas
* prove additional theorems about `getLsb` applied to other operations
the proof becomes 
```
example (v : Std.BitVec n)  : 0#0 ++ v = BitVec.cast (by omega) v := by ext; simp
```
> feat: lemmas for BitVec

- Std/Tactic/Omega/Frontend.lean
- Std/Tactic/Omega/OmegaM.lean
- test/omega/test.lean
Closes #562, reported by @dwrensha.
> fix: revert OmegaM state when not multiplying out

- Std/Tactic/Omega/Config.lean
- Std/Tactic/Omega/Frontend.lean
- Std/Tactic/Omega/Int.lean
- Std/Tactic/Omega/OmegaM.lean
- test/omega/test.lean
```
example {a : Nat} (_ : a < min a b) : False := by omega 
example {a : Nat} (_ : max a b < b) : False := by omega 
example {a b : Nat} (_ : a = 7) (_ : b = 3) : min a b = 3 := by omega
example {a b : Nat} (_ : a + b = 9) : (min a b) % 2 + (max a b) % 2 = 1 := by omega
example {a : Int} (_ : a < if a ≤ b then a else b) : False := by omega
example {a b : Int} : (if a < b then a else b - 1) ≤ b := by omega
```
* Upon encountering `min a b`, add the facts `min a b <= a` and `min a b <= b` (similarly for max)
* Upon encountering `natAbs a`, add the facts `a <= natAbs a` and `-a <= natAbs a`
* If `splitMinMax := true`, allow the case split on `min a b = if a <= b then a else b` (similarly for max) as needed
* If `splitNatAbs := true`, allow the case split on `natAbs a = if 0 <= a then a else …
> feat: omega handles min, max, if

- Std/Data/Array/Lemmas.lean
this is possible after the fix in
https://github.com/leanprover/lean4/pull/3197 and will hopefully help
with array bounds checking.
> feat: reduce assumptions from `size_swap!`

- Std/Data/Nat/Lemmas.lean
- test/decidability.lean
I ran into the lack of these predicates (specifically the first one) will working on `BitVec` lemmas (manipulating `decide` terms).
These are copied from Mathlib, and we'll need to remember to remove the instances when this is merged.
> chore: upstream decidability instances for bounded Nats

- Std/Data/BitVec/Lemmas.lean
`BitVec.zero_is_unique` is a duplicate of `BitVec.eq_nil`, so we deprecate the former as an alias
> refactor: deprecate duplicate BitVec lemma

- Std/Data/BitVec/Basic.lean
- Std/Data/BitVec/Bitblast.lean
- Std/Data/BitVec/Lemmas.lean
- Std/Data/Nat/Bitwise.lean
- Std/Data/Nat/Init/Lemmas.lean
- Std/Data/UInt.lean
Mathlib already has this as `Nat.two_pow_pos`.
> chore: fix Nat.pow_two_pos -> Nat.two_pow_pos

- Std/Data/Nat/Lemmas.lean
- Std/Logic.lean
- Std/Tactic/Omega/Int.lean
- Std/Tactic/Omega/Logic.lean
We just added `Classical.and_not`, but it is causing too many disambiguation errors with `_root_.and_not` in Mathlib, so I am giving it a longer name.
> chore: rename Classical.and_not

- README.md
Std4 differs from mathlib with respect to this. To avoid confusion we clarify this in the contribution section of the README.
> chore: clarify that contributions should happen via forks.

- Std/Data/List/Lemmas.lean
This PR is a subset of the changes proposed in #233.
As pointed out by @fgdorais [here][fg split comment], #233 needed to be split in smaller contributions. This is the first PR in that direction.
[fg split comment]: https://github.com/leanprover/std4/pull/233#issuecomment-1702464142
> feat: migrate lemmas about `List.cons` and `List.concat` from Mathlib

- Std/Tactic/Omega/Frontend.lean
- Std/Tactic/Omega/Int.lean
- Std/Tactic/Omega/OmegaM.lean
- test/omega/test.lean
Also, add facts about `x % k ^ i` atoms when `k` is a non-zero literal.
This makes reasoning about `x % 2 ^ i` terms (e.g. in BitVec arguments) much more pleasant.
> feat: omega only replaces mod with div when the modulus is a literal

- Std/Data/BitVec/Bitblast.lean
Proves that adding a bitvector to its own complement yields the all-ones bitvector.
This result is necessary for showing that bitvectors are a commutative ring in mathlib.
> feat: x + ~~~x = allOnes

- Std/Data/BitVec/Basic.lean
These instances are simply `BitVec.ofInt`/`BitVec.ofNat`, but having them is a prerequisite for some mathlib typeclasses (in particular, `CommRing`)
> feat: `IntCast` and `NatCast` instances for bitvectors

- Std/Data/Nat/Bitwise.lean
- Std/Data/Nat/Lemmas.lean
Mostly these are not upstreamed from Mathlib, as Mathlib proves these results in greater generality than we can here. I've used the same names, but in the Nat namespace.
> feat: lemmas about Nat.pow

- Std/Data/BitVec/Bitblast.lean
- Std/Data/BitVec/Lemmas.lean
A corollary of `add_not_self`: subtracting `x` from the all-ones bitvector is the same as taking the complement of `x`
> feat: prove `allOnes _ - x = ~~~x`

- Std/Data/BitVec/Lemmas.lean
Some more lemmas that rewrite `toFin` applied to a bitwise operation (`and`/`or`/`xor`)
> feat: lemmas about `BitVec.getLsb` and bitwise ops (and/or/xor)

- Std/Data/BitVec/Lemmas.lean
Ensure all lemmas about `toNat`/`toFin` applied to an operation take their arguments explicitly.
It was pointed out in #636 that the new `toFin_` lemmas had inconsistent argument implicitness, which brought to light also the inconsistency of existing related `toNat_` lemmas. Both are addressed with the current PR.
> refactor: improve consistency of BitVec lemmas

- Std/Data/Int/Init/DivMod.lean
- Std/Data/Int/Init/Lemmas.lean
- Std/Data/Int/Order.lean
- Std/Data/List/Basic.lean
- Std/Data/Nat.lean
- Std/Data/Nat/Basic.lean
- Std/Data/Nat/Gcd.lean
- Std/Data/Nat/Init/Basic.lean
- Std/Data/Nat/Init/Dvd.lean
- Std/Data/Nat/Init/Gcd.lean
- Std/Data/Nat/Init/Lemmas.lean
- Std/Data/Nat/Lemmas.lean
- Std/Tactic/Omega/Constraint.lean
- Std/Tactic/Omega/IntList.lean
- Std/Tactic/Omega/MinNatAbs.lean
This moves a bunch of lemmas around to remove the remaining lemmas in Std.Data.Nat.Lemmas from Omega's dependencies.
It may lose some organization, but at least the remaining lemmas could potentially use Omega.
> chore: Drop Std.Data.Nat.Lemmas from Omega dependencies.

- Std/Data/Rat/Basic.lean
- Std/Data/Rat/Lemmas.lean
This PR extracts the new lemma `mk_den_one`, previously introduced in #611 and uses it to golf some proofs.
> feat: add `Rat.mk_den_one` simp lemma

- Std/Data/BitVec/Lemmas.lean
Simplify the proof of `BitVec.eq_of_toFin_eq`, which used `ext` and `simp`, into a proof that just matches on the bitvector arguments and uses `rfl`.
> chore: simplify the proof of `BitVec.eq_of_toFin_eq`

- Std/Data/Rat/Basic.lean
- Std/Data/Rat/Lemmas.lean
Following [this discussion](https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/Compute.20roots.20of.20polynomials/near/420643573)*, I would like to remove the `ext` attribute from `Rat` (and manually add the `Rat.ext` lemma).
* The discussion was essentially that `ext` digging into ℚ is like `ext` digging into ℂ and ℂ's `ext` was removed.
In the specific case, calling `ext` on an equality of polynomials with rational coefficients entered the polynomials through the equality of their coefficients (expected and desirable) and then broke up the (rational) coefficients into their numerators and denominators (undesirable). This leads you astray more often than it is helpful.
This uncovered that `local ext` does not really make the attribute local -- #618.  However, with …
> Rat: remove `ext` attribute

- Std/Data/BitVec/Lemmas.lean
This characterizes when the `msb` is 1 in terms of an arithmetic inequality.
> feat: ∀(x : BitVec w.succ), msb x = 1 iff x >= 2^w

- Std/Data/BitVec/Lemmas.lean
Adds a lemma to rewrite `toFin (~~~x)`.
There is a slight inconsistency with `toNat_not`, which takes its argument implicitly.
I followed the other `toFin_` lemmas in making the argument explicit, but choose not to change `toNat_not` to keep this PR focussed.
Morally, the result of `toFin (~~~x)` should be `Fin.last _ - x.toFin`. However, this doesn't typecheck, as `Fin.last n` is of type `Fin (n + 1)`. Alternatives that do type-check are:
*  Inline the definition of `Fin.last` to get `⟨2^w - 1, Nat.sub_lt (Nat.two_pow_pos _)⟩`
* Use `Fin.cast`, as in `(Fin.last (2^w-1)).cast (_ : 2^w-1+1 = 2^w)`
* Define `Fin.last' (h : n \neq 0) : Fin n` (using one of the preceding options), and use that
I've chosen to go with the first option (inlining), since it seemed the most straightforward.
> feat: `BitVec.toFin_not` lemma

- Std/Data/BitVec/Lemmas.lean
We choose to define the shift on natural numbers and then coercing back to fin with `Fin.ofNat`' to maintain `defeq`.
While shifting is defined on `Fin` [in core](https://github.com/leanprover/lean4/blob/5cc0c3f145ffa623a617ca31387d7f589802c1d3/src/Init/Data/Fin/Basic.lean#L71-L72), the type signature is `Fin -> Fin -> Fin`, while the type signature we want is `Fin -> Nat -> Fin`.
An alternative `rhs` using the `Fin`'s definition of shift would be:
```lean
x.toFin <<< (Fin.ofNat' n (Nat.two_pow_pos _))
```
but this is not a def-eq anymore, so we choose the current implementation instead.
> feat: add toFin_shiftLeft

- Std/Data/BitVec/Lemmas.lean
Add a simp-lemma that normalizes `BitVec.toFin (BitVec.ofNat _ _)` into `Fin.ofNat'`
> feat: `BitVec.toFin_ofNat` lemma

- Std/Data/List/Count.lean
- Std/Data/List/Lemmas.lean
- Std/Data/List/Perm.lean
This change addresses the FIXME for lemmas about `List.erase`. Namely replacing `DecidableEq` assumptions in lemmas that prove things about functions involving `BEq` with `BEq` + `LawfulBEq` assumptions. While there are at least two other APIs that need this refactor (see the other touched files) this is minimal enough to make LeanSAT work again.
Should I also attempt to refactor all the other things for completeness sake or is this enough for now?
> refactor: erase to BEq/LawfulBEq

- scripts/runLinter.lean
This is helpful in downstream projects, so they don't need to create a `nolints.json` if they never need it.
> feat: runLinter doesn't error if nolints.json is missing

- Std/Data/BitVec/Lemmas.lean
Adds a few simple simp-lemmas about `BitVec.cast`.
Also changes the two existing lemmas (`toNat_cast` and `getLsb_cast`) to be more consistent. In particular, `getLsb_cast` now takes it's proof of width-equality explicitly, just like `toNat_cast` already does, and the variable names have been aligned.
> feat: simp-lemmas about `BitVec.cast`

- Std/Data/BitVec/Lemmas.lean
- test/bitvec.lean
I think readability is improved if we make this a simp rule, but it is currently too easy to create simp loops with it on.
> chore: lemma for BitVec.ofFin to .ofNat

- Std/Data/BitVec/Basic.lean
We already have a simp lemma that rewrites `OfNat.ofNat` into `BitVec.ofNat`.
This PR extends that by rewriting `Nat.cast` into `BitVec.ofNat` as well, making `BitVec.ofNat` the canonical simp-normal form for all ways to turn a `Nat` into a `BitVec`.
> feat: Add a simp lemma `Nat.cast x = BitVec.ofNat _ x`

- Std/Data/BitVec/Lemmas.lean
Adds a lemma `negOne_eq_allOnes`, ensuring that `(-1 : BitVec w)` and `-1#w` are both (transitively) simplified to `allOnes w`.
The choice of `allOnes` as the canonical form was inspired by the fact we already have a few simp-lemmas about it, such as `toNat_allOnes` but also `not_def`. The downside is that `allOnes` is itself defined as `-1`, so we can get a simp loop with `simp [allOnes]`.
> feat: establish `BitVec.allOnes` as simp normal form

- Std.lean
- Std/Lean/Meta/Iterator.lean
- Std/Tactic/SolveByElim.lean
- Std/Tactic/SolveByElim/Backtrack.lean
This doesn't remove the import so an existing signature is unchanged, but it effectively replaces the Nondet and implicit MLList dependency in Backtrack and SolveByElim with an iterator.
The iterator has a narrower interface, but a simpler design.
This is a step towards upstreaming library search to Lean 4.
> chore: refactor Backtrack and SolveByElim to remove Nondet dependency

- Std/Util/CheckTactic.lean
- test/array.lean
This also changes the current `#check_simp` command to require a term reduces.
> feat: Introduce `#check_simp !~>` to check a term is in normal form.

- README.md
The README documentation build instructions are missing the `-R` flag that needs to be passed to `lake`. This generates configuration files that are read by [doc-gen4](https://github.com/leanprover/doc-gen4).
> docs: fix documentation build instructions

- Std/Data/List/Basic.lean
- Std/Data/List/Lemmas.lean
- Std/Data/List/Perm.lean
`List.merge` the merge step from merge sort (without any ordering assumptions). This will be useful to streamline and optimize `ac_rfl`.
Note that `List.merge` exists in Mathlib but the Mathlib implementation is not tail recursive and it uses a decidable relation instead of a `Bool` relation. A Mathlib adaptation PR is in progress: https://github.com/leanprover-community/mathlib4/tree/fgdorais-patch-list-merge
> feat: `List.merge` and lemmas

- README.md
This PR adds the changes requested by @digama0 in #669, explaining how to reset build configuration after creating the docs.
> docs: add further build info

- Std/Data/List/Lemmas.lean
Indent the subsequent theorem statement by 4 spaces.
> style: indent subsequent theorem statement

- Std/Data/Array/Lemmas.lean
Here is a description of each theorem being added. Given some array:
1. If you swap element at position i with that at j, then element at j in the new array (after swap) will be the element that was at i in the old array (before the swap)
2. If you swap element at position i with that at j, then element at i in the new array will be the element that was at j in the old array 
3. If you swap element at position i with that at j, then all elements that are neither at positions i nor j remain unchanged from what they were before the swap
4. If you swap element at position i with that at j, get a new array, then in this new array if you swap element at position i with that at j again, what you get is the original array you had before any of the swaps
5. If you swap element at position i with …
> feat: add more theorems about `Array.swap`'s basic properties

- Std/Tactic/Init.lean
they are already defined in
https://github.com/leanprover/lean4/blob/3ab1c23500658a1997b342fad15f499d7c482365/src/Init/Tactics.lean#L370
and
https://github.com/leanprover/lean4/blob/3ab1c23500658a1997b342fad15f499d7c482365/src/Init/Core.lean#L797
> chore: remove upstreamed `rfl` macro rules

- Std/Data/List/Lemmas.lean
https://github.com/leanprover/std4/pull/272 unnecessarily specialized the universes of `List.map_take`.
I'm going to merge this immediately, as it's holding up bump Mathlib's Std dependency.
> fix: map_take had unnecessarily specialized universes

- Std/Data/List/Lemmas.lean
These non-simp lemmas are easier to use in rewrites.
As discussed on Zulip: <https://leanprover.zulipchat.com/#narrow/stream/348111-std4/topic/RFC.3A.20.60List.2Etake_drop.60.20and.20.60List.2Edrop_take.60/near/428435321>
> feat: better `List.take_drop` and `List.drop_take`

- Std/CodeAction/Deprecated.lean
- Std/Data/Array/Lemmas.lean
- Std/Data/Array/Monadic.lean
- Std/Data/HashMap/WF.lean
- Std/Lean/Meta/AssertHypotheses.lean
- Std/Linter/UnnecessarySeqFocus.lean
Inference of array indexing proofs has improved. This PR removes those that no longer need to be given explicitly.
I *think* this is an improvement but would like a second opinion.
> chore: removed unnecessary array indexing proofs

- Std/Tactic/Init.lean
This is not used in Mathlib; all uses can just become `trivial`. Let's remove the unnecessary duplication.
https://github.com/leanprover-community/mathlib4/pull/11679
> chore: remove triv tactic

- Std/Data/List/Basic.lean
- Std/Data/List/Lemmas.lean
- Std/Data/List/Perm.lean
I've aimed to more consistently use BEq instead of DecidableEq where that is feasible and rely on a LawfulBEq for proofs where needed.
> chore: use BEq instead of DecidableEq in List additional ops

- Std/Data/HashMap/Basic.lean
Port of leanprover/lean4#3887 to Std. I confirmed that the same bug exists in the Std hashmap and the same fix works for it.
> perf: linearity in HashMap.erase

- Std/Tactic/PrintPrefix.lean
- test/print_prefix.lean
Minor cleanup of `PrintPrefix.lean`, plus using `ppSignature` for showing the results (with `pp.tagAppFns` so that the constants are clickable).
> feat: cleanup PrintPrefix, use ppSignature

- Std/Data/Array/Basic.lean
- Std/Data/List/Init/Attach.lean
Fixes #711. Implementation of `List.attachWith`, which has a type signature somewhere between `List.attach` and `List.pmap`, and use it to define `List.attach`.
> feat: List.attachWith

- Std/Data/HashMap/Basic.lean
Create usage examples in `Std.Data.HashMap.Init` similar to `Std.Data.List.Basic`
Closes #469
> doc: add examples to `Std.Data.HashMap.Init` docs

- Std.lean
- Std/Tactic/ShowUnused.lean
- test/show_unused.lean
`#show_unused decl1 decl2 ..` will highlight every theorem or definition in the current file not involved in the definition of declarations `decl1`, `decl2`, etc. The result is shown both in the message on  `#show_unused`, as well as on the declarations themselves.
This is requested periodically on Zulip. The most recent related mention I can find is [`#delete_unused_by`](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/.23delete_unused_by/near/430912325) which is a slight variation which removes the theorems instead of highlighting them.
> feat: `#show_unused` command

- Std/Data/Array.lean
- Std/Data/Array/Init/Lemmas.lean
- Std/Data/Array/Lemmas.lean
- Std/Data/Fin/Lemmas.lean
- Std/Data/List.lean
- Std/Data/List/Init/Lemmas.lean
- Std/Data/List/Lemmas.lean
`Std.Data.Array.Lemmas` should not be a dependency of `Std.Data.Fin.Lemmas`. Move the necessary theorems to `*.Init.*`.
> chore: remove cross-cutting dep

- Std/Classes/Order.lean
- Std/Data/List/Lemmas.lean
- Std/Data/RBMap/Basic.lean
- Std/Data/RBMap/Lemmas.lean
- Std/Data/RBMap/WF.lean
This adds the function `RBNode.reverse` which left-right reverses an RBNode. This is not order-preserving, but it is still an important symmetry and it simplifies some reasoning about left and right rebalancing. It can even be lifted to an operation on `RBSet` and `RBMap` provided it reverses the comparator.
> feat: RBNode.reverse

- Std/Tactic/Classical.lean
Refactor of `classical` so there is a `MetaM` / `TacticM` level interface.
(This I think will allow Mathlib's tauto to use this, instead of `classical!`, thereby removing the last use of `classical!`. It's a positive change regardless.)
> chore: monadic implementation of classical

- Std/Data/RBMap/Alter.lean
- Std/Data/RBMap/Lemmas.lean
Using #734 , we can find and remove all unnecessary theorems from `Alter.lean`, minimizing the compile load for someone who just wants the `alter` function without proved properties.
> chore: move theorems RBMap.{Alter -> Lemmas}

- Std/Data/Array/Lemmas.lean
- Std/Data/List/Lemmas.lean
See [here](https://github.com/leanprover/std4/commit/27766a2bb4a2c743197bcaf56e205b097669f47e#diff-4236f31530e7cfa1ed2974fdb2f8c4d8fbac8cce221f2661b74913ffd6a86bffR10). This was incorrectly merged by the bot in f612c2224402d04fc4aba252296441f7310046dd. The commit 92a9edabd60c57b7652d3237cfcd146190089cd4 fixes the build, but right now on `nightly-testing` the results from `Data.List.Init.Lemmas` are not available when imorting `Data.List.Lemmas`, which I believe is wrong.
> fix: Data.List.Lemmas shoud import Data.List.Init.Lemmas on nightly-testing

- .docker/gitpod/Dockerfile
- .gitpod.yml
Add docker files and .gitpod.yml to enable use of Gitpod with std4. Both of these are copied from mathlib with modifications for std4
I have opened std4 in Gitpod and tested,
- building std4
- running tests with make
- building and view docs
related to #565
> chore: add .gitpod.yml and .docker/gitpod/Dockerfile

- Std/Data/Array/Merge.lean
- Std/Lean/Meta/DiscrTree.lean
In preparation for adding analogous theorems to List. Many of the termination proofs in this file are no longer needed because of `omega`.
> chore: cleanup and shorten names in Array.Merge

- Std/Data/Nat/Gcd.lean
Lemma `Nat.exists_coprime` does not need to assume `gcd m n > 0`.
> feat(Nat/Gcd): drop an unneeded assumption

- Std/Data/List/Lemmas.lean
Also rename to `List.get_mk_zero`
to leave room for a version about `(0 : Fin l.length)`.
> fix: don't cast to `Option` in `List.get_zero`

- Std/Tactic/Lint/Simp.lean
- Std/Tactic/SqueezeScope.lean
- lean-toolchain
These are pre-emptive fixes for nightly-2024-05-01 (which doesn't exist yet) prepared using a local toolchain. We can merge into `nightly-testing` as soon as it lands.
> chore: pre-emptive fixes for nightly-2024-05-01

- Std/Logic.lean
* Move the theorem from `Mathlib.Logic.Function.Basic` to Std.
* We need this theorem to prove `String.splitOn_of_valid`.
> refactor: move `Function.id_def` from mathlib

- Std/Data/RBMap/Basic.lean
There are `union` and `sdiff` function implementations for `Std.RBSet`. But there are no `Union` and `SDiff` class instances, which I find inconsistent.
Is there any reason behind this? I tried asking in Zulip ([thread](https://leanprover.zulipchat.com/#narrow/stream/348111-std4/topic/Union.20and.20SDiff.20instances.20for.20Std.2ERBSet)). Got no answers so far, prohibiting having these instances. So, I am making this PR. (there was on [old version of this PR](https://github.com/leanprover/std4/pull/771), but I messed up sync of my fork, so making the new one)
> chore: add `Union` and `SDiff` instances for `Std.RBSet`

- Batteries/Data/Array/Basic.lean
In preparation for https://github.com/leanprover/lean4/pull/3969 landing, we fix some deprecation warnings.
> chore: deprecations in dot notation

- Batteries/Data/List/Basic.lean
This used to be defined via `Array.ofFn`
but `Array.ofFn.go` is defined by well-founded recursion (slow to reduce)
and used `Array.push` (quadratic complexity on lists). Since mathlib relies on
reducing `List.ofFn`, use a structurally recursive definition here.
> refactor: structurally recursive List.ofFn

- Batteries/Data/List/Basic.lean
At present, the simplifier always unfolds the definition of the function
`List.modifyHead`. This behavior hinders the simplifier from using
lemmas about the function, hence the following changes:
* Remove the `simp` attribute from the function.
* Add two `simp` lemmas for it.
> refactor: remove `@[simp]` from `List.modifyHead`

- Batteries/Data/BinomialHeap/Basic.lean
- Batteries/Data/PairingHeap.lean
- Batteries/Data/RBMap/Alter.lean
these were missed by the linter, which is probably a bug that
is fixed or made fire less often with
https://github.com/leanprover/lean4/pull/4192
> fix: unused variables

- Batteries/Tactic/Alias.lean
- test/alias.lean
As [reported on Zulip](https://leanprover.zulipchat.com/#narrow/stream/348111-batteries/topic/Bad.20interaction.20of.20alias.20and.20deprecated.20.28since.20.3A.3D.20_.29/near/439757782).
> fix: support `since` in `@[deprecated] alias`

- Batteries/Data/Array/Basic.lean
Adds safe Nat indexed variants of Array functions: `getN`, `setN`, `swapN`, `swapAtN`, and `eraseIdxN`.
> feat: safe Nat indexed Array functions using get_elem_tactic

- Batteries/Lean/Name.lean
There is another private copy of `isInternalName` up in lean. This makes the implementations identical.
Later I will move the upstream copy to `Lean.Name` and then remove this.
> chore: align `isInternalName` with upstream version

- Batteries/Data/String.lean
- Batteries/Data/String/Basic.lean
- Batteries/Data/String/Matcher.lean
- test/kmp_matcher.lean
Mostly this is just for clearer organization of dependencies when we start working on String theorems. Some of the material still in `Basic` can move upstream.
> chore: split KMP for strings into separate file

- Batteries/Data/Nat/Basic.lean
- Batteries/WF.lean
This is from @nomeata's Zulip comment: https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/Contributing.20a.20strong.20induction.20for.20lists/near/442796959. It can subsume, for example, mathlib's `Finset.strongInductionOn` and `Multiset.strongInductionOn`.
In situations where it doesn't make sense to extract a goal into a top-level `theorem`/`def`, `induction _ using measureRec` will be more convenient than `let rec` -> `termination_by` -> `decreasing_by` -> `exact`.
> feat: `measureRec` for strong induction use cases

- Batteries/Data/HashMap/WF.lean
I've been running into breakages in these proofs: this will make me slightly saner.
Hopefully these will all be redundant in any case soon, with the new HashMap.
> chore: squeeze simps in HashMap.WF

- Batteries/Data/Array/Lemmas.lean
- Batteries/Data/Fin/Lemmas.lean
- Batteries/Data/HashMap/WF.lean
- Batteries/Data/List/EraseIdx.lean
- Batteries/Data/List/Lemmas.lean
- Batteries/Data/List/Pairwise.lean
- Batteries/Tactic/Lint/Frontend.lean
- lean-toolchain
- test/congr.lean
This shouldn't be merged until leanprover/lean4#4400 lands in a nightly.
> chore: adaptations for leanprover/lean4#4400, List look-up normal form

- Batteries/Data/UInt.lean
Reported by @eric-wieser on [Zulip](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/Fintype.20Char.3F/near/445317208).
Some lemmas are about `val` instead of `toNat` so they may need update if core changes the implementation of `UIntX` types.
> feat: add  simps and `toNat` lemmas for `UIntX` types

- lean-toolchain
This only affects the behaviour of `lake`.
> chore: bump toolchain to v4.9.0-rc3

- Batteries/Data/String/Lemmas.lean
- Batteries/Linter/UnnecessarySeqFocus.lean
- Batteries/Linter/UnreachableTactic.lean
- lean-toolchain
Co-authored-by: Mario Carneiro <di.gama@gmail.com>
Co-authored-by: Bulhwi Cha <chabulhwi@semmalgil.com>
---
The base branch of this pull request is the branch for https://github.com/leanprover-community/batteries/pull/857.
> chore: avoid nonterminal simps in String/Lemmas

- lakefile.lean
As far as I understand, no human or automation ever runs doc-gen on `Batteries`. Instead documentation is generated as part of Mathlib's documentation.
If that is the case, I would like to remove the `doc-gen` dependency from the `lakefile`.
(This is on the path to moving to a `lakefile.toml`, and eventually possibly deprecating `meta if` in `lakefile.lean`.)
> chore: remove 'meta if' from lakefile

- Batteries/Data/HashMap/Lemmas.lean
It would probably not be a good use of anyone's time to work on that sorry right now, and there was [some confusion on Zulip](https://leanprover.zulipchat.com/#narrow/stream/224796-Geographic-locality/topic/New.20York.20City.2C.20USA/near/449684763) today, so I suggest removing the `proof_wanted`.
> chore: remove `proof_wanted` in HashMap.Lemmas

- Batteries/Data/UnionFind/Basic.lean
In today's attempt to adapt to changes in Lean https://github.com/leanprover/lean4/pull/4595 I ran into a broken proof in `UnionFind`, and discovered lots more non-terminal simps making it unnecessarily complicated to fix, so I've removed them all here, too.
> chore: remove nonterminal simps in UnionFind

- Batteries/Tactic/Lint/Misc.lean
The `unusedHavesSuffices` linter is run by default now: remove the part of its docstring which says otherwise.
> doc: fix outdated docstring

- Batteries/Tactic/Lint/Frontend.lean
- scripts/runLinter.lean
Extend `getChecks` to allow an additional list of linters, which is always run. This can be used downstream to e.g. enable the `docBlameThm` or `explicitVarsOfIff` linters without modifying batteries.
As part of this, we
- update fix the function docstring (which was quite outdated anyway)
- remove the `useOnly` option: the equivalent effect can be achieved by filtering the list of linters afterwards; *adding* linters cannot, hence must be performed in this function. (That said, I'm happy to add this functionality back if desired.)
- rename a variable `dflt` to the more readable `default`
- adjust the logic of the #lint command accordingly
Note that `test/lint_simpNF.lean` lies on this (the docBlame linter warns there) - so this changed is already tested.
> feat: allow configuring additional linters to run

- test/lint_lean.lean
Adds a file in `test/` for running the environment linters on `lean4` itself.
Everything is commented out, because it is too slow to run in Batteries CI, and there are still many failures. Nevertheless it is useful to have a coordinated place to run these linters from, until such a time as we can move environment linters up.
I have addressed many in 
* https://github.com/leanprover/lean4/pull/4621
* https://github.com/leanprover/lean4/pull/4620
* https://github.com/leanprover/lean4/pull/4616
I have not touched the `explicitVarsOfIff` linter, but I would be happy to review a PR making progress on this.
> chore: test file for linting lean4

- Batteries/Data/Array/Lemmas.lean
Core uses `nil` instead of `empty` for some array lemmas and I keep getting caught by that, so I'm proposing to add aliases for the `empty` variants. I'm also proposing to add `mem_singleton` since that one comes up often enough that I'd like to avoid going through list every time.
> feat: some array lemma aliases

- .github/workflows/build.yml
- lakefile.lean
lean-action will now run the linter via `lake lint` instead of running it directly with `lake exe runLinter`
> chore: bump lean-action to v1

- test/MLList.lean
This test is timing-sensitive, and has [spuriously failed](https://github.com/leanprover-community/batteries/actions/runs/10036728715/job/27735044947?pr=887) before. Increase the timings slightly to make it less easy to race.
> fix: flaky test

- Batteries/Data/List/Basic.lean
It turns out using `List` is faster than `Array` in the auxiliary functions for `splitAt` and `splitAtD`. It's about a 10% improvement (and much more for splitAtD when there is lots of padding).
I was a little surprised at first, so double checked my timings from `#time #eval ...` with a `hyperfine "lean --run ..."` benchmark.
> feat: faster splitAt

- Batteries.lean
- Batteries/Data/ByteSubarray.lean
Alternative to #836. While this is not quite a drop-in replacement for users of Mathlib's `ByteSlice`, it offers the same functionality while using the same basic structure as core's `Subarray` type.
This fixes the issues I raised in #836 but I'm also happy with compromises. For example, I personally think `ByteSlice` is a better name than `ByteSubarray`. I'm also a fan of the offset/length approach but this seems to much of a divergence from `Subarray`.
> feat: add `ByteSubarray`

- scripts/runLinter.lean
This ensures that linters work even if the target module hasn't imported `Batteries.Tactic.Lint`.
> feat: runLinter uses ``withImportModules #[module, Batteries.Tactic.Lint]``

- Batteries/Data/Fin/Lemmas.lean
- Batteries/Data/List/Perm.lean
- lean-toolchain
Two lemmas upstreamed, and one lemma in Lean had `@[simp]` removed because it fired too often.
> chore: adaptations for nightly-2024-09-02

- Batteries/Data/String/Basic.lean
As requested on [zulip](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/deprecated.20String.2EtoAsciiByteArray/near/467132158).
This had been deprecated in Mathlib without a replacement.
> chore: upstream/undeprecate String.toAsciiByteArray

- Batteries/Tactic/Where.lean
As [reported on Zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/.23where.20broken/near/464403221).
> feat: `#where` supports weak options

- .github/workflows/nightly_detect_failure.yml
In line with /leanprover/lean4#5015 use emoji variants of ✅️ and ❌️ in the entire Lean universe.
> chore: use emoji variant of unicode characters

- .gitpod.yml
This PR changes the .gitpod.yml file to run `elan self update` and `lake build`. This ensures that contributors don't have to wait for batteries files to build when they open a file
> chore: update .gitpod.yml to pre-build Batteries

- Batteries.lean
- Batteries/Data/ByteArray.lean
- Batteries/Data/FloatArray.lean
These have been recently requested on [Zulip](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Regarding.20map.20and.20extract.20for.20Byte.2FFloatArrays/near/452971124).
> feat: add `map` and `mapM` for scalar array types

- scripts/runLinter.lean
Reported in [this Zulip thread](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Configuring.2Fmodernizing.20runLinter/near/472003381).
The fix is similar to what happened already to shake [here](https://github.com/leanprover-community/mathlib4/blob/9890065b5f32e2ab14314294d1b497d229d7c865/Shake/Main.lean#L538).
Ultimately, the reason is that `Lean.Json.pretty` does not add a trailing `\n` to the resulting string.
> fix: add trailing line-break in nolints.json

- Batteries/Data/Fin/Lemmas.lean
`rfl` for ground terms will reduce at transparency `.all`, even if the current transparency is `.default`. Maybe it's prudent to not rely on this corner case, and have more explicit proofs.
> refactor: avoid relying on rfl's behavior on ground terms

- .github/workflows/test_mathlib.yml
This will only run once it is on master, so we can only test in production.
Will require a secret token installed.
Also needs an update at Mathlib to actually report back, but we could add that afterwards.
> feat: automatically test Mathlib against Batteries PRs

- Batteries/Data/Array/Lemmas.lean
- Batteries/Data/List/Lemmas.lean
While looking at the TODO in my recently merged PR I realized that it's obsolete now, as the mentioned theorem already exists in core as its iff variant.
That motivated me to convert the theorem I added to its iff version. I guess this is a breaking change, but since the PR was just merged yesterday, the only usage of the theorem is probably in Array/Lemmas.
> fix: remove List.erase_of_forall_bne and replace with List.erase_eq_self_iff_forall_bne

- Batteries/Classes/SatisfiesM.lean
- Batteries/Data/List/Basic.lean
- Batteries/Data/List/Lemmas.lean
- Batteries/Data/RBMap/Alter.lean
- Batteries/Logic.lean
- Batteries/WF.lean
https://github.com/leanprover/lean4/pull/5338 is still a draft PR and the exact behaviour remains to be decided, but these changes were flagged by an intermediate version.
I think these changes are fine, and getting them in here reduces the number of balls in the air keeping Batteries/Mathlib adapted to that PR.
> chore: cleanup some unused arguments

- scripts/runLinter.lean
Batteries' linter previously encoded the compile-time search path into its executable. This means the linter would break if run from a different environment or machine. It now uses the information from the user's environment to determine the correct search path, making it reasonably portable.
> fix: use user's Lean search path in linter

- lean-toolchain
Exactly the same as `v4.13.0-rc1`, so this is just for consistency with Mathlib.
> chore: move to v4.13.0-rc3

- Batteries/Data/List/Lemmas.lean
The theorem `List.isEmpty_iff_eq_nil` had already been moved to
`Init.Data.List.Lemmas` and renamed `List.isEmpty_iff`.
> chore: remove duplicate theorem about lists

- Batteries/Data/Rat/Basic.lean
- Batteries/Data/Rat/Lemmas.lean
With this change, `#simp Rat.ofScientific 314 false 2` in mathlib gives `3.14`.
This relates to https://github.com/leanprover/lean4/pull/5725
> feat: characterize `OfScientific.ofScientific` on `Rat`

- Batteries/Util/ProofWanted.lean
- test/proof_wanted.lean
This was requested by Terence Tao [on Zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Is.20a.20.60definition_wanted.60.20keyword.20possible.3F/near/477325788)
Closes #938
> fix: make `proof_wanted` not report unused variables

- Batteries/Lean/Expr.lean
c.f. https://github.com/leanprover/lean4/pull/5729
No particular preference regarding naming: favoring the existing upstream name seems easiest.
> chore: deprecate `Expr.lambdaArity` in favor of existing upstream version

- Batteries/Tactic/PrintPrefix.lean
- test/print_prefix.lean
This fix makes it so that `#print prefix` does nothing when there is no identifier. Note that this doesn't actually fix the underlying issue: `#print prefix` is still horribly slow downstream of Mathlib.
Closes #995
> fix: print prefix bug

- Batteries/Data/List/Basic.lean
- Batteries/Data/List/Lemmas.lean
- Batteries/Data/List/Perm.lean
Mathlib adaptation PR https://github.com/leanprover-community/mathlib4/pull/17985 needs delegation before this can be merged.
See zulip [discussion](https://leanprover.zulipchat.com/#narrow/channel/348111-batteries/topic/.60List.2EmodifyNth.60/near/477340629).
> chore: rename List.modifyNth->modify and insertNth->insertIdx

- Batteries/Data/List/Basic.lean
> chore: fix List.modify/insertIdx doc-strings

- Batteries/CodeAction/Misc.lean
* The code action now works even on `induction e using rec` custom eliminators
* It also respects custom eliminators via the `@[custom_eliminator]` attribute
* It also works even if the induction already has branches, it will only add branches that are uncovered to the end of the match
* If the induction has a `|_ => tac` arm, it will delete this arm and use `tac` instead of `sorry` to fill in all the missing branches
> feat: improve induction code action

- .github/workflows/labels-from-status.yml
This workflow assigns `awaiting-review` or `WIP` labels to new PRs, and it removes `awaiting-review`, `awaiting-author`, or `WIP` label from closed PRs.
It does not modify labels for open PRs that already have one of the `awaiting-review`, `awaiting-author`, or `WIP` labels.
> chore: add unlabeled PR workflow

- Batteries/Data/Nat/Gcd.lean
Without this change, when faced with
```
if gcd m n = 1 then
f (gcd m n)
else
0
```
the compiler will fail to perform CSE and compute `gcd m n` twice, as the `Decidable` instance is inferred as the one in this PR, which obscures the implementation from the compiler.
See https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Compiler.20inserts.20.60instDecidableCoprime.60.3F/near/444709593
Deleting the instance would also work.
> perf: inline the `Decidable (Coprime _ _)` instance

- Batteries/Data/String/Lemmas.lean
These proofs now work before and after leanprover/lean4#6039.
> chore: robustify some String proofs

- Batteries/Data/List/Monadic.lean
Quick followup to #1034, applying Eric's suggestion to the other lemma, too.
> chore: cleanup proof of satisfiesM_foldlM

- Batteries.lean
- Batteries/Classes/SatisfiesM.lean
- Batteries/Data/HashMap/Basic.lean
- Batteries/Lean/EStateM.lean
- Batteries/Lean/Except.lean
- Batteries/Lean/LawfulMonad.lean
- Batteries/Lean/SatisfiesM.lean
- BatteriesTest/satisfying.lean
Enables:
```
example (xs : Array Expr) : MetaM { ts : Array Expr // ts.size = xs.size } := do
let r ← satisfying (xs.size_mapM inferType)
return r
```
by showing that for the basic monads and monad transformers, one can lift the `SatisfiesM` predicate to a monadic value in `Subtype`.
> feat: sugar for SatisfiesM

- Batteries/Tactic/OpenPrivate.lean
- BatteriesTest/OpenPrivateDefs.lean
- BatteriesTest/openPrivate.lean
This allows users to include more than one space between the tokens, and will also allow building once #6012 is merged in Lean.
> fix: use two tokens for open private/export private

- Batteries/Classes/SatisfiesM.lean
When experimenting with `SatisfiesM` recently, I've found these inconvenient, as they too eagerly invoke `.run`, when one might still want to be doing arbitrary-monad reasoning.
> chore: remove @[simp] attributes from monad-specific SatisfiesM lemmas

- Batteries/Data/Range/Lemmas.lean
Non-squeezed simps were breaking on nightly-testing. Squeezing.
> chore: cleanup breaking non-terminal simps

- README.md
Thank you all for this amazing library!
This is a very small edit to the readme. The `require` directive in `lakefile.lean` needs the `git` token for specifying a Git version.
> fix: Readme.md needs "git" token in lakefile.lean

- Batteries/Data/Array/Basic.lean
- Batteries/Data/Array/Lemmas.lean
- Batteries/Data/Fin.lean
- Batteries/Data/Fin/Basic.lean
- Batteries/Data/Fin/Fold.lean
- Batteries/Data/Fin/Lemmas.lean
- Batteries/Data/List.lean
- Batteries/Data/List/Basic.lean
- Batteries/Data/List/FinRange.lean
Harmonize with Mathlib, renaming Fin.list to List.finRange and Fin.enum to Array.finRange.
> refactor: add List.finRange and Array.finRange

- README.md
c.f. https://github.com/leanprover/lean4/blob/4969ec9cdb9a4a6d148b46df3850cdabae3f70ae/src/lake/README.md#toml-require
Reported at https://leanprover.zulipchat.com/#narrow/channel/270676-lean4/topic/Importing.20a.20repository.20in.20.60lakefile.2Etoml.60/near/485018063
> fix: dependency syntax for a reservoir+git lakefile.toml

- Batteries/Data/Fin/Basic.lean
- Batteries/Data/Fin/Fold.lean
Define `dfoldl` and `dfoldr` from their monadic versions to avoid code duplication. The cost is that they now require `Type _` instead of `Sort _`. However, induction principles are already available to deal with `Prop` so there is no overall loss.
> refactor: dependent fold for `Fin`

- Batteries/Data/List.lean
- Batteries/Data/List/ArrayMap.lean
- BatteriesTest/ArrayMap.lean
- scripts/test.lean
Calling List.toArray followed by Array.map currently implies a superfluous memory allocation: first, the list is converted to an array, then the array is mapped again. We can avoid this easily, by creating a new function List.toArrayMap.
Suggested by `kim-em` [on zulip](https://leanprover.zulipchat.com/#narrow/channel/144837-PR-reviews/topic/.2312190.20.60have.60.20vs.20.60let.60.20linter/near/486752051).
> feat: add List.toArrayMap

- Batteries.lean
- Batteries/Data/NameSet.lean
Taken [from ImportGraph](https://github.com/leanprover-community/import-graph/blob/9cb79405471ae931ac718231d6299bfaffef9087/ImportGraph/RequiredModules.lean); originally written by `kim-em`.
> feat: add further API about `Lean.NameSet`

- Batteries/Data/Fin.lean
- Batteries/Data/Fin/OfBits.lean
- Batteries/Data/Nat/Basic.lean
- Batteries/Data/Nat/Lemmas.lean
Adds new functions `Nat.ofBits` and `Fin.ofBits` and associated lemmas.
Prequel for #1078 which adds `BitVec.ofFn`.
> feat: add `Nat.ofBits` and `Fin.ofBits`

- Batteries/Classes/Order.lean
- Batteries/Data/RBMap/Lemmas.lean
In https://github.com/leanprover/lean4/pull/6821, new simp lemmas were added. One of the nonterminal `simp` tactics in `RBMap.lean` now closes the only remaining goal, so that the succeeding tactic failed with "no goals to be solved". The fix is to remove the obsolete code.
> fix(failing build): remove now-unneeded tactics after nonterminal simp

- Batteries/Data/Array/Lemmas.lean
This is functional, but I don't have much experience, so any review is much appreciated.
> feat: prove `Array.toList_erase`

- Batteries/Data/Array/Lemmas.lean
- Batteries/Data/Vector/Basic.lean
- Batteries/Data/Vector/Lemmas.lean
The `eq_of_beq` proof is a bit hairy, and I couldn't find a proof that didn't use `Vector.ext`, so I moved the instance to be with the other `Vector` lemmas. All review is greatly appreciated.
> feat: add `LawfulBEq` instance for `Vector`

- README.md
Currently, the [`proof_wanted`](https://github.com/search?q=repo%3Aleanprover-community%2Fbatteries+proof_wanted+language%3ALean&type=code&l=Lean) link brings up two results relating to the implementation and testing of `proof_wanted`. Adding `NOT path:/proof_?wanted/` prevents this, making the link marginally more useful.
> chore: remove meta results for README `proof_wanted` link

- .github/workflows/labels-from-status.yml
Always run on target branch instead of the PR branch to have permission to write labels.
> chore: fix labels-from-status

- Batteries/Data/ByteArray.lean
- Batteries/Data/FloatArray.lean
Also adds a decidable equality instance for `ByteArray`.
> fix: use ext attribute to generate ext lemmas for `ByteArray` and `FloatArray`

- Batteries.lean
- Batteries/Control/Lawful/MonadLift.lean
- Batteries/Lean/LawfulMonadLift.lean
This PR adds `LawfulMonadLift` and `LawfulMonadLiftT` type classes to add laws to the existing `MonadLift(T)` type class, which only contains the lifting operation. We also derive `Lawful` instances for common liftings.
One thing to note: I'm not sure how the `simp` direction should go in `monadLift_bind`, and whether we should have `simp` for both specific version (`ExceptT.lift_bind`) and generic version.
If this PR goes well, I will add more `Lawful` type classes to `Monad{Functor/Control/State/Option/etc}`.
> feat: add `LawfulMonadLift`

- Batteries/Control/Lawful/MonadLift.lean
This PR reverses the simp direction of lawful `monadLift` operations, so that they got pulled inward rather than outward. This is similar to the direction in classes like `MulHomClass` and also consistent with the [Haskell documentation](https://hackage.haskell.org/package/transformers-0.5.6.2/docs/Control-Monad-Trans-Class.html#t:MonadTrans).
We also duplicate the lemmas for `monadLift` and `liftM` to help in rewriting, which matches on syntax only. We set the simp attribute for lemmas about `liftM` only, since simp can look into definitions.
Finally, we add the canonical lifting operation from `Id` to any monad `m` via its `pure` function.
> chore: fix simp direction for `monadLift_bind`

- Batteries/Logic.lean
@b-mehta accidentally pushed a commit to `main` (surprised this is possible!) which I'm reverting now.
> chore: revert accidental commit to `main`

- Batteries/Lean/EStateM.lean
This makes the code work both with and without leanprover/lean4#3010, making it easier to test/merge/revert that PR.
Right now the files are inconsistent regarding the use of implicit universe arguments, and so with the Lean change above, the downstream file ends up more general than the upstream one.
> chore: remove explicit universes from `EStateM` results

- Batteries/Logic.lean
Currently, the `Sort u` argument to `heq_iff_eq` has name `α✝`, making it inaccessible using `(_ := _)` syntax. As such, the change here refers to `α` by name so that it has name `α` instead. 
Note that this PR does not change the implicitness of any of the variables. 
This is the smallest change I could think of which would have the desired effect (making the type argument accessible) and change nothing else, but if there is a preferred alternate option, I am happy to go with that instead.
> chore(Logic): give implicit argument an accessible name

- Batteries/Classes/Order.lean
- Batteries/Classes/SatisfiesM.lean
- Batteries/Data/RBMap/Lemmas.lean
This PR generalizes some typeclasses. They were found using a linter.
[#mathlib4 > Linter for generalizing type class hypotheses](https://leanprover.zulipchat.com/#narrow/channel/287929-mathlib4/topic/Linter.20for.20generalizing.20type.20class.20hypotheses)
> chore: generalize `TransCmp` -> `OrientedCmp`

- Batteries/Data/Nat/Basic.lean
This definition has become irreducible in v4.19.0-rc2, which blocks reduction of `Nat.sqrt`, as well as `IsSquare` and `Nat.minFac` in mathlib, both functions which are used for decidability there. Furthermore, marking `Nat.sqrt.iter` as `semireducible` locally does not make those reduce appropriately. Further still, `decide +kernel` - which is meant to ignore irreducible tags - fails to see through `Nat.sqrt.iter`, so the only solution is this one.
> chore: mark `Nat.sqrt.iter` as semireducible

- Batteries/Data/HashMap/Basic.lean
As [discussed on Zulip](https://leanprover.zulipchat.com/#narrow/channel/113489-new-members/topic/Failed.20to.20synthesize.20GetElem), making `Batteries.HashMap` an abbrev for `Std.HashMap` makes all instances for `Batteries.HashMap` also apply to `Std.HashMap` as soon as `Batteries.HashMap` is imported. Since the `GetElem` instances for the two hash maps are in conflict with each other, this leads to problems. This PR changes the abbrevation to a one-field structure.
> fix: use a one-field structure for `Batteries.HashMap`

- Batteries/Tactic/Exact.lean
All the functions in core use the spelling `DefEq`, so batteries should match them.
> chore: deprecate mis-cased Lean.MVarId.assignIfDefeq

- Batteries/Data/List/Lemmas.lean
Reverts leanprover-community/batteries#1198. Note: The changes to decidability were reverted for now for later consideration in Q3 this year.
> Revert "adaptation for lean 4 pr 7855"

- Batteries/Data/Vector/Lemmas.lean
There are no lemmas for interacting with `Vector.tail`. This PR adds some basic API for it. (I also think we should define it using a match rather than an if-then-else but that's a core problem).
> feat: add `Vector.tail` API

- Batteries/Data/Vector/Lemmas.lean
Renames two lemmas added in  #1234 that were misnamed.
> fix: Rename `tail` lemmas

- Batteries/Tactic/Lint/Simp.lean
- BatteriesTest/lint_simpNF.lean
`simpNF` was claiming `simp` could prove something when in reality `simp` couldn't prove it.
This was because `simpNF` used the wrong `Meta.Config`, so this PR fixes that.
> fix(simpNF): use correct Meta configuration

- .github/workflows/discover-lean-pr-testing.yml
This fixes the discover-lean-pr-testing workflow which was incorrectly filtering branches by looking for changes to `lakefile.lean`, but Batteries uses `lakefile.toml`.
The workflow was copied from Mathlib's equivalent workflow, but this key difference wasn't properly adapted. This caused the branch relevance detection to work incorrectly - branches that should have been automatically merged were either being skipped or incorrectly flagged as needing manual review.
Changed the file filtering logic to use `lakefile.toml` instead of `lakefile.lean` in the branch diff check.
> fix: use lakefile.toml instead of lakefile.lean in discover workflow

- Batteries/Tactic/Init.lean
- BatteriesTest/by_contra.lean
This works around https://github.com/leanprover/lean4/issues/8643.
Also adjusts a test to actually verify that the proof uses decidability, rather than using proof irrelevence.
Fixes #1196
> fix: do not create Decidable subgoals from by_contra

- .github/workflows/test_mathlib.yml
This goes along with https://github.com/leanprover/lean4/pull/8933 and https://github.com/leanprover-community/mathlib4/pull/26286, see zulip discussion at [#nightly-testing > moving to a fork](https://leanprover.zulipchat.com/#narrow/channel/428973-nightly-testing/topic/moving.20to.20a.20fork/with/525242440)
> chore: update CI to use mathlib4-nightly-testing fork

- Batteries/Data/Array/Basic.lean
We changed the internal representation of `Subarray` while preserving all of its functionality. However, the constructor cannot be used as before. This PR fixes a call of `Subarray.mk` in Batteries. See: https://github.com/leanprover/lean4/pull/8947
> fix batteries after Subarray->Slice migration

- Batteries/Data/BitVec/Lemmas.lean
Also replace some proofs by `grind`.
> chore: `@[grind]` annotations for `BitVec` lemmas

- .github/workflows/nightly_detect_failure.yml
Updates the github actions for nightly testing to use `[nightly-testing branch](https://github.com/leanprover-community/batteries/tree/nightly-testing)` ([nightly-testing branch](https://github.com/leanprover-community/batteries/tree/nightly-testing)) instead of [branch#nighly-testing](https://github.com/leanprover-community/mathlib4/tree/nighly-testing) which is a dead link. Similar to leanprover-community/mathlib4#26363.
> fix: nightly testing zulip message

- Batteries/Tactic/Lint/Misc.lean
The `unusedHavesSuffices` linter error talks about proofs, so this PR adds in a check that the `have` is indeed introducing a proposition. This will be necessary in the next release because Lean will convert `let`s to `have`s automatically to cache which ones are nondependent, and, for example, `do` notation can elaborate into expressions that have unused `let`s, which we don't want to be flagged by this linter.
After the next Lean release, this linter should be updated look for nondependent `Expr.letE` expressions rather than `letFun`s.
> feat: make `unusedHavesSuffices` linter only apply to propositions

- Batteries/Data/Nat.lean
- Batteries/Data/Nat/Digits.lean
As discussed in https://github.com/leanprover/lean4/pull/8673.
> feat: lemmas about `Nat.toDigits`

- Batteries.lean
- Batteries/Control/LawfulMonadState.lean
- Batteries/Control/OptionT.lean
This PR defines a `LawfulMonadStateOf` type-class for instances of `MonadStateOf` where the `get` and `set` operations are compatible in the expected ways, and adds instances for basic examples like `StateT` and `EStateM`.
> feat: Laws for `MonadStateOf` instances

- Batteries/Data/String/Lemmas.lean
Fixes the breakage due to changing the definition of `String.prev`.
> fix `Batteries.Data.String.Lemmas` on nightly-testing

- Batteries/Lean/EStateM.lean
This PR fills in lemmas about `EStateM.run` and `EStateM.run'` applied to various standard monad operations, as well as those for error and state monads.
> feat: lemmas about running `EStateM` computations

- Batteries/Control/LawfulMonadState.lean
This PR makes `σ` a semiOutParam in `LawfulMonadState`. Otherwise, `LawfulMonadStateOf.toLawfulMonad` is an illegal instance. This is in line with `MonadStateOf`.
> fix: use `semiOutParam` in `LawfulMonadState`

- Batteries/Data/List/Basic.lean
Has this ever been used? Is it common in other languages' List APIs? It's just cost me half an hour and I'd love to avoid having it cost me more!
Anyone wanting to keep this function could please assist by reverting 0de31883 on the nightly-testing branch, and then removing the reliance on the now private `filterMapTR.go`. (I'm alternatively happy to review a PR refactoring the relevant code in Lean to make that non-private, by making it a top-level declaration. But either this PR or that needs to happen before the next release.)
> chore: propose deprecation of List.fillNones

- Batteries/Data/Char/AsciiCasing.lean
- Batteries/Data/String/Lemmas.lean
`Std.Classes.Ord.String` has been moved to `Init.Data.Ord.String`, so we need to remove two obsolete imports.
> remove `Std` imports that are now in `Init`

- Batteries/Data/Nat/Basic.lean
This enables us to run `Nat.sqrt` on large (e.g. million digit) numbers.
> feat: better Newton starting point in `Nat.sqrt`

- Batteries/Control/Nondet/Basic.lean
- Batteries/Data/MLList/Basic.lean
- Batteries/Lean/Meta/Basic.lean
- BatteriesTest/nondet.lean
This adds instances for `MLLists` and `Nondet`, and fixes definitions that assumed two unrelated monad instances.
> feat: more support for `AlternativeMonad`
